magnopus-opensource/connected-spaces-platform

Tools/WrapperGenerator/.csharpierrc.json
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache
Tools/WrapperGenerator/Templates/C/Partials/Parameter.mustache
Tools/WrapperGenerator/Templates/CSharp/Class.mustache
Tools/WrapperGenerator/Templates/CSharp/Partials/Class/Method/Method.mustache
UnitTesting/Templates/Exports/exports.cpp.jinja2
UnitTesting/Templates/Exports/exports.h.jinja2
UnitTesting/Templates/Tests/CSharp/tests.cs.jinja2
UnitTesting/Templates/Tests/JavaScript/tests.js.jinja2

[OF-814] test: unit test parameters of class functions

---

Library/include/CSP/Multiplayer/Components/VideoPlayerSpaceComponent.h
Library/src/Multiplayer/Components/VideoPlayerSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/VideoPlayerSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/VideoPlayerSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Tests/CSharp/src/Tests/MultiplayerTests.cs
Tests/Web/html/tests/multiplayer_tests.js
Tests/src/PublicAPITests/ComponentTests/VideoPlayerComponentTests.cpp

- Added IsEnabled property to Video component via IEnableableComponent interface
- Updated script bindings to add the new property

[OW-1404] feat: Video component IsEnabled property

---

Tests/src/PublicAPITests/UserSystemTests.cpp

Our CICD automations were running tests using non-standard users with non-standard roles on MCS.
In order to have full confidence that CSP works as it should for client applications, we have changed the MCS test users to have standard roles.
That however started causing two tests to fail, where we were attempting to create users, bypassing email verification - something typical end-users cannot do.
So, we updated our tests to validate that when a regular user attempts to create another another user, we get the expected responses.

[NT-0] fix: user tests for regular test accounts

---

Library/include/CSP/Common/Array.h
Library/include/CSP/Common/Optional.h
Tests/src/InternalTests/CommonTypeTests/Array.cpp
Tests/src/InternalTests/NewFeatureTests.cpp

[OF-1079] test: add `csp::common::Array` tests

---

Tests/src/InternalTests/CommonTypeTests/Vector3.cpp
Tests/src/InternalTests/CommonTypeTests/Vector4.cpp

[OF-1100] test: test csp::common::Vector3 and 4

---

Library/docs/source/_static/interop.gif
README.md

A new gif showing off the real-time interoperability of CSP far better than our previous one.

[NT-0] doc: update to the interoperability gif

---

Library/include/CSP/Systems/EventTicketing/EventTicketing.h
Library/include/CSP/Systems/EventTicketing/EventTicketingSystem.h
Library/src/CSP/Systems/EventTicketing/EventTicketing.cpp
Library/src/CSP/Systems/EventTicketing/EventTicketingSystem.cpp
Tests/src/PublicAPITests/EventTicketingSystemTests.cpp

[OF-1076] feat: client apps can query whether a space requires a ticket to enter or not

---

Library/src/Systems/Spaces/SpaceSystem.cpp
Library/src/Systems/Spaces/SpaceSystemHelpers.cpp
Library/src/Systems/Spaces/SpaceSystemHelpers.h
Tests/src/InternalTests/SpaceHelperTests.cpp

[OF-1061] refac: Create helper functions and internal tests

---

.gitignore

[OF-1093] fix: Add .npmrc to gitignore

---

Tests/src/PublicAPITests/MultiPlayerTests.cpp

[OF-1006] fix: Update Nightly C++ Tests

---

Library/include/CSP/Common/StringFormat.h
Tests/src/InternalTests/CommonTypeTests/StringFormat.cpp

[OF-1098] test: test `csp::common::StringFormat`

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/include/CSP/Systems/SystemsManager.h
Library/src/CSPFoundation.cpp
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Systems/EventTicketing/EventTicketingSystem.cpp
Library/src/Systems/SystemsManager.cpp
Tests/CSharp/src/TestHelper.cs
Tests/CSharp/src/Tests/AnchorSystemTests.cs
Tests/CSharp/src/Tests/AssetSystemTests.cs
Tests/CSharp/src/Tests/ConversationSystemTests.cs
Tests/CSharp/src/Tests/ECommerceSystemTests.cs
Tests/CSharp/src/Tests/EventTicketingSystemTests.cs
Tests/CSharp/src/Tests/GraphQLSystemTests.cs
Tests/CSharp/src/Tests/LODTests.cs
Tests/CSharp/src/Tests/MaintentanceSystemTests.cs
Tests/CSharp/src/Tests/MultiplayerTests.cs
Tests/CSharp/src/Tests/PointOfInterestSystemTests.cs
Tests/CSharp/src/Tests/SettingsSystemTests.cs
Tests/CSharp/src/Tests/SpaceSystemTests.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/ECommerceSystemTests.cpp
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache

[OF-1107] feat: ECommerceSystem and GetProductInformation

---

Tests/src/PublicAPITests/MultiPlayerTests.cpp

[OF-1006] fix: Fix nightly SignalR test

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/include/CSP/Systems/SystemsManager.h
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Systems/SystemsManager.cpp
Library/src/Web/HttpPayload.cpp
Library/src/Web/HttpPayload.h
Library/src/Web/WebClient.cpp
Tests/CSharp/src/TestHelper.cs
Tests/CSharp/src/Tests/AnchorSystemTests.cs
Tests/CSharp/src/Tests/AssetSystemTests.cs
Tests/CSharp/src/Tests/ConversationSystemTests.cs
Tests/CSharp/src/Tests/ECommerceSystemTests.cs
Tests/CSharp/src/Tests/EventTicketingSystemTests.cs
Tests/CSharp/src/Tests/GraphQLSystemTests.cs
Tests/CSharp/src/Tests/LODTests.cs
Tests/CSharp/src/Tests/MaintentanceSystemTests.cs
Tests/CSharp/src/Tests/MultiplayerTests.cs
Tests/CSharp/src/Tests/PointOfInterestSystemTests.cs
Tests/CSharp/src/Tests/SettingsSystemTests.cs
Tests/CSharp/src/Tests/SpaceSystemTests.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/ECommerceSystemTests.cpp
Tests/src/PublicAPITests/GraphQLSystemTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

We are seeking to publish a new patch version of CSP to address feedback from developers that a CSP crash can occur if services return a 400 error code with a non-json payload format.

[OF-1117] merge develop to staging

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/include/CSP/Systems/SystemsManager.h
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Systems/SystemsManager.cpp
Library/src/Web/HttpPayload.cpp
Library/src/Web/HttpPayload.h
Library/src/Web/WebClient.cpp
Tests/CSharp/src/TestHelper.cs
Tests/CSharp/src/Tests/AnchorSystemTests.cs
Tests/CSharp/src/Tests/AssetSystemTests.cs
Tests/CSharp/src/Tests/ConversationSystemTests.cs
Tests/CSharp/src/Tests/ECommerceSystemTests.cs
Tests/CSharp/src/Tests/EventTicketingSystemTests.cs
Tests/CSharp/src/Tests/GraphQLSystemTests.cs
Tests/CSharp/src/Tests/LODTests.cs
Tests/CSharp/src/Tests/MaintentanceSystemTests.cs
Tests/CSharp/src/Tests/MultiplayerTests.cs
Tests/CSharp/src/Tests/PointOfInterestSystemTests.cs
Tests/CSharp/src/Tests/SettingsSystemTests.cs
Tests/CSharp/src/Tests/SpaceSystemTests.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/ECommerceSystemTests.cpp
Tests/src/PublicAPITests/GraphQLSystemTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

[OF-1117] merge staging to main

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Updating a reference to Foundation to be 'CSP'

[NT-0] Update issue templates

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Tests/src/PublicAPITests/ECommerceSystemTests.cpp

[OF-1111] feat: GetCheckoutInformation

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Web/WebClient.cpp
Tests/src/PublicAPITests/ECommerceSystemTests.cpp

[OF-1108] feat: Adds ECommerce Create/Get Cart

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/src/Systems/ECommerce/ECommerce.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Tests/src/PublicAPITests/ECommerceSystemTests.cpp

[OF-1109] feat: Add UpdateCartInformation functionality

---

Library/include/CSP/Systems/ECommerce/ECommerceSystem.h

[NT-0] doc: Fix ecommerce typo

---

Library/include/CSP/Systems/ECommerce/ECommerceSystem.h

[NT-0] doc: Fix Ecommerce GetCart SpaceID typo

---

Tests/src/PublicAPITests/UserSystemTests.cpp

[NT-0] test: Update Agora Token Test

---

Tests/src/PublicAPITests/SpaceSystemTests.cpp

[NT-0] test: Update UpdateUserRolesTest

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp

[OF-1027] feat!: Update ResetUserPassword to token-change-password endpoint

---

Examples/Basic Framework/Web/helpers.js
Examples/Basic Framework/Web/index.js
Examples/Basic Framework/Web/package.json
Examples/Initialising Foundation/Web/helpers.js
Examples/Initialising Foundation/Web/index.js
Examples/Initialising Foundation/Web/package.json

[OW-1380] chore: Update web examples to CSP 4.9.0

---

.github/workflows/codeql.yml

Skip code analysis on github runner

---

Examples/Basic Framework/Web/index.js
Examples/Initialising Foundation/Web/index.js

[OB-2916] fix: Update web example endpoints

---

Library/src/Systems/ECommerce/ECommerce.cpp

[OB-2931] fix: Add checks when parsing products

---

teamcity/Config.py
teamcity/templates/unity/NativePluginBuildProcessor.cs

[NT-0] fix: exclude iOS debug binaries

---

Tests/premake5.lua

[NT-0] fix: Fix premake project kind type

---

teamcity/Config.py
teamcity/templates/unity/NativePluginBuildProcessor.cs

Staging 4.10.1

---

teamcity/BuildNPMWebPackage.py
teamcity/PublishCSPForUnity.py

[NT-0] fix: publish pipeline fixes

---

premake5_helpers.lua

Staging 4.10.4

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp

[OB-2954] fix!: Add UserId to ResetUserPassword

---

Library/src/Web/MaintenanceApi/MaintenanceApi.cpp

[OB-2936] fix: Correct URLs for oprod maintenance windows

---

Library/include/CSP/CSPFoundation.h
Tools/WrapperGenerator/CSharpWrapperGenerator.py
Tools/WrapperGenerator/MetadataTypes.py
Tools/WrapperGenerator/Templates/TypeScript/Partials/Class.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/Enum.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/GlobalFunction.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/Interface.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/Method.mustache
Tools/WrapperGenerator/TypeScriptWrapperGenerator.py

[OF-1128] fix: include doc comments in JS wrapper

---

Library/src/Systems/Users/Authentication.cpp
Library/src/Web/EmscriptenWebClient/EmscriptenWebClient.cpp
Tests/Web/html/tests/usersystem_tests.js
Tests/Web/html/tests/usersystem_tests_helpers.js
Tests/src/PublicAPITests/LogSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTestHelpers.h
Tests/src/PublicAPITests/UserSystemTests.cpp

[OB-2974] fix: wasm header case fix

---

teamcity/GenerateReadme_NEW.py
teamcity/templates/readme/readme.md.jinja2

[OF-1148] fix: fix package readme generation

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp

[OF-864] feat: add `ResendVerificationEmail`

---

Tools/WrapperGenerator/Templates/TypeScript/Partials/Method/TaskMethod.mustache

[OB-3027] fix: fix optional bool regression

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp
Tools/WrapperGenerator/Templates/TypeScript/Partials/Method/TaskMethod.mustache
teamcity/GenerateReadme_NEW.py
teamcity/templates/readme/readme.md.jinja2

Staging 4.14.0

---

Library/include/CSP/Systems/Quota/Quota.h
Library/src/Systems/Quota/Quota.cpp
Library/src/Systems/Quota/QuotaSystem.cpp

Updated use of the logging macro to fix issues. Resolved warnings related to initialisation order.

[NT-0] fix: Fixed issue with logging macros

---

Library/include/CSP/Systems/Quota/Quota.h
Library/src/Systems/Quota/Quota.cpp
Library/src/Systems/Quota/QuotaSystem.cpp

Updated use of the logging macro to fix issues. Resolved warnings related to initialisation order.

Staging 4.15.0

---

Library/include/CSP/CSPCommon.h

[NT-0] refac: ensure platform define always set

---

Examples/Basic Framework/Web/index.js
Examples/Basic Framework/Web/package.json
Examples/Basic Framework/Web/yarn.lock
Examples/Initialising Foundation/Web/package.json
Examples/Initialising Foundation/Web/yarn.lock

- Fixed call to createSpace in basic web example
- Updated web examples to CSP 4.15.1

[NT-0] fix: Fixed call to createSpace in basic web example and updated examples to CSP 4.15.1

---

Library/include/CSP/Systems/Users/Authentication.h
Library/src/Systems/Users/Authentication.cpp

[OF-865] feat: parse EmailNotConfirmed failure

---

Library/include/CSP/Services/WebService.h
Library/include/CSP/Systems/Assets/Asset.h
Library/include/CSP/Systems/Quota/Quota.h
Library/include/CSP/Systems/Users/Authentication.h
Library/src/Services/WebService.cpp
Library/src/Systems/Assets/Asset.cpp
Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/Quota/Quota.cpp
Library/src/Systems/Users/Authentication.cpp
Tests/src/PublicAPITests/AssetSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTestHelpers.h
Tests/src/PublicAPITests/UserSystemTests.cpp
teamcity/BuildNPMWebPackage.py
teamcity/GenerateReadme_NEW.py
teamcity/templates/readme/readme.md.jinja2

Staging 4.16.0

---

Library/include/CSP/Systems/Quota/Quota.h
Library/src/Systems/Quota/Quota.cpp
Tests/src/PublicAPITests/QuotaSystemTests.cpp

[OF-1194] fix!: Remove AllowReductions

---

.gitmodules
Library/include/CSP/Systems/Users/UserSystem.h
Library/premake5.lua
Library/src/Systems/Users/UserSystem.cpp
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/Method/EventMethod.mustache
UnitTesting/Templates/Exports/exports.cpp.jinja2
UnitTesting/Templates/Exports/partials/classes/functions/event/event.cpp.jinja2
UnitTesting/Templates/Exports/partials/classes/functions/event/event.h.jinja2
UnitTesting/Templates/Tests/CSharp/partials/classes/functions/event/event.cs.jinja2
UnitTesting/Templates/Tests/JavaScript/partials/classes/functions/event/event.js.jinja2
UnitTesting/scripts/Config.py
UnitTesting/scripts/GenerateTests.py
UnitTesting/templates/exports/partials/classes/functions/functions.cpp.jinja2
UnitTesting/templates/exports/partials/classes/functions/functions.h.jinja2
UnitTesting/templates/tests/csharp/partials/classes/functions/functions.cs.jinja2
UnitTesting/templates/tests/javascript/partials/classes/functions/functions.js.jinja2

Staging 4.17.1

---

Tests/CSharp/src/TestHelper.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/InternalTests/UniqueStringTest.cpp
Tests/src/PublicAPITests/AnchorSystemTests.cpp
Tests/src/PublicAPITests/AssetSystemTests.cpp
Tests/src/PublicAPITests/ComponentTests/AudioComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CollisionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ECommerceComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FiducialMarkerComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FogComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ImageComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LightComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LinkComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/PortalComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ReflectionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/SplineComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/VideoPlayerComponentTests.cpp
Tests/src/PublicAPITests/ConversationSystemTests.cpp
Tests/src/PublicAPITests/EventTicketingSystemTests.cpp
Tests/src/PublicAPITests/GraphQLSystemTests.cpp
Tests/src/PublicAPITests/LODTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/PointOfInterestSystemTests.cpp
Tests/src/PublicAPITests/QuotaSystemTests.cpp
Tests/src/PublicAPITests/ScriptSystemTests.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp
Tests/src/TestHelpers.h

[OF-1066] fix: Add GetUniqueString

---

Examples/Basic Framework/Web/helpers.js
Examples/Basic Framework/Web/index.js
Examples/Basic Framework/Web/package.json
Examples/Basic Framework/Web/yarn.lock
Examples/Initialising Foundation/Web/package.json
Examples/Initialising Foundation/Web/yarn.lock

Updated web examples to CSP 4.17.1

[OW-1567] refac: Update web examples to 4.17.1

---

Examples/Basic Framework/CSharp/Foundation-Unity-Example/Packages/manifest.json
Examples/Initialising Foundation/CSharp/Foundation-Unity-Example/Packages/manifest.json
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Assets/Scripts/HelloWorld.cs
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Packages/manifest.json

[OSB-10] fix: update unity examples

---

Library/src/Multiplayer/Conversation/ConversationSystem.cpp
Library/src/Multiplayer/SignalR/SignalRClient.cpp
Library/src/Services/ApiBase/ApiBase.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp

[OF-1196] fix: Remove C style casting

---

Library/include/CSP/Multiplayer/Components/AnimatedModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/AudioSpaceComponent.h
Library/include/CSP/Multiplayer/Components/AvatarSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ButtonSpaceComponent.h
Library/include/CSP/Multiplayer/Components/CollisionSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ConversationSpaceComponent.h
Library/include/CSP/Multiplayer/Components/CustomSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ECommerceSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ExternalLinkSpaceComponent.h
Library/include/CSP/Multiplayer/Components/FiducialMarkerSpaceComponent.h
Library/include/CSP/Multiplayer/Components/FogSpaceComponent.h
Library/include/CSP/Multiplayer/Components/LightSpaceComponent.h
Library/include/CSP/Multiplayer/Components/PortalSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ReflectionSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ScriptSpaceComponent.h
Library/include/CSP/Multiplayer/Components/SplineSpaceComponent.h
Library/include/CSP/Multiplayer/Components/StaticModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/VideoPlayerSpaceComponent.h
Library/src/Multiplayer/Components/ButtonSpaceComponent.cpp
Library/src/Multiplayer/Components/CollisionSpaceComponent.cpp
Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Library/src/Multiplayer/Components/ECommerceSpaceComponent.cpp
Library/src/Multiplayer/Components/ExternalLinkSpaceComponent.cpp
Library/src/Multiplayer/Components/FiducialMarkerSpaceComponent.cpp
Library/src/Multiplayer/Components/FogSpaceComponent.cpp
Library/src/Multiplayer/Components/ImageSpaceComponent.cpp
Library/src/Multiplayer/Components/LightSpaceComponent.cpp
Library/src/Multiplayer/Components/PortalSpaceComponent.cpp
Library/src/Multiplayer/Components/ReflectionSpaceComponent.cpp
Library/src/Multiplayer/Components/VideoPlayerSpaceComponent.cpp

[OF-1214] refac: implement transform interfaces

---

Tools/WrapperGenerator/MetadataTypes.py
Tools/WrapperGenerator/Parser.py
Tools/WrapperGenerator/Templates/CSharp/Partials/Class/Method.mustache
Tools/WrapperGenerator/Templates/TypeScript/Partials/Method.mustache

[OF-665] feat: wrap `[[deprecated]]` in wrappers

---

Examples/Basic Framework/CSharp/Foundation-Unity-Example/Packages/manifest.json
Examples/Basic Framework/CSharp/Foundation-Unity-Example/ProjectSettings/ProjectVersion.txt
Examples/Basic Framework/CSharp/Foundation-Unity-Example/README.md
Examples/Initialising Foundation/CSharp/Foundation-Unity-Example/Packages/manifest.json
Examples/Initialising Foundation/CSharp/Foundation-Unity-Example/ProjectSettings/ProjectVersion.txt
Examples/Initialising Foundation/CSharp/Foundation-Unity-Example/README.md
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Packages/manifest.json
Examples/Multiplayer/CSharp/Foundation-Unity-Example/ProjectSettings/ProjectVersion.txt
Examples/Multiplayer/CSharp/Foundation-Unity-Example/README.md

https://magnopus.atlassian.net/browse/OPE-1504

[OPE-1504] Update examples to Unity 2022 LTS

---

Library/include/CSP/Systems/Log/LogSystem.h

NOTE: Tests are not needed for this as we currently already test `LogSystem` in our C++ tests, and wrapper-related tests are handled by our wrapper generator unit tests.

[OF-1155] refac: export all `LogSystem` functions

---

teamcity/requirements.txt

Updated requirements.txt to include the distutils
module dependency.

Staging 4.18.0

---

Library/src/Memory/MemoryManager.cpp

[OF-940] refac: ensure allocator created first

---

Library/include/CSP/Systems/Settings/SettingsSystem.h
Library/src/Systems/Settings/SettingsSystem.cpp
Tests/CSharp/src/Tests/SettingsSystemTests.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/SettingsSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

BREAKING CHANGE: This change removes the `UserId` parameter from all public `SettingsSystem` functions.

[OF-1226] refac!: Modify SettingsSystem API

---

Library/src/Multiplayer/SpaceEntity.cpp

Fixes an issue where we were passing a String instead of a C-String to CSP_LOG_*.

[NT-0] fix: more logging fixes

---

Library/src/Multiplayer/ComponentBase.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp

Staging 4.19.0 #2

---

teamcity/requirements.txt

Reverts magnopus-opensource/connected-spaces-platform#347

[NT-0] fix: revert #347

---

Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Systems/EventTicketing/EventTicketingSystem.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

[NT-0] fix: update services api

---

Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Multiplayer/SpaceEntitySystem.cpp
Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Library/src/Systems/EventTicketing/EventTicketingSystem.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

Staging 4.23.1

---

teamcity/templates/unity/NativePluginBuildProcessor.cs

[OB-3490] fix: do not strip symbols for VisionOS

---

Library/src/Systems/ECommerce/ECommerce.cpp

[OB-3493] fix: properly validate optionals

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/src/Multiplayer/ComponentBase.cpp
Library/src/Multiplayer/Components/AnimatedModelSpaceComponent.cpp
Library/src/Multiplayer/Components/AudioSpaceComponent.cpp
Library/src/Multiplayer/Components/AvatarSpaceComponent.cpp
Library/src/Multiplayer/Components/ButtonSpaceComponent.cpp
Library/src/Multiplayer/Components/CollisionSpaceComponent.cpp
Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Library/src/Multiplayer/Components/CustomSpaceComponent.cpp
Library/src/Multiplayer/Components/ECommerceSpaceComponent.cpp
Library/src/Multiplayer/Components/ExternalLinkSpaceComponent.cpp
Library/src/Multiplayer/Components/FiducialMarkerSpaceComponent.cpp
Library/src/Multiplayer/Components/FogSpaceComponent.cpp
Library/src/Multiplayer/Components/GaussianSplatSpaceComponent.cpp
Library/src/Multiplayer/Components/ImageSpaceComponent.cpp
Library/src/Multiplayer/Components/LightSpaceComponent.cpp
Library/src/Multiplayer/Components/PortalSpaceComponent.cpp
Library/src/Multiplayer/Components/ReflectionSpaceComponent.cpp
Library/src/Multiplayer/Components/ScriptSpaceComponent.cpp
Library/src/Multiplayer/Components/SplineSpaceComponent.cpp
Library/src/Multiplayer/Components/StaticModelSpaceComponent.cpp
Library/src/Multiplayer/Components/VideoPlayerSpaceComponent.cpp

- Add type-safe getters for the 6 ReplicatedValue types
- Refactored components to use these functions

[OF-1314] refac: ComponentBase type getters

---

Examples/Basic Framework/CSharp/Foundation-Unity-Example/Assets/Scripts/HelloWorld.cs
Examples/Multiplayer/CSharp/Csp-Unity-VisionPro-Example/Assets/Scripts/HelloWorld.cs
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Assets/Scripts/HelloWorld.cs

[OPE-1738] fix: Moved CSP tick loop start after login in examples

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/src/Multiplayer/Components/TextSpaceComponent.cpp
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Tests/src/PublicAPITests/ComponentTests/TextComponentTests.cpp

This pull request will add missing references to TextSpaceComponent:
1. add component type enum entry
2. fix entry ref in component
3. add script bindings for TextSpaceComponent
4. add component construction based on component type enum
Add tests to verify above is working as intended.

Completed component addition and added tests

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/include/CSP/Multiplayer/EventParameters.h
Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/include/CSP/Systems/Sequence/Sequence.h
Library/include/CSP/Systems/Sequence/SequenceSystem.h
Library/include/CSP/Systems/SystemsManager.h
Library/src/Multiplayer/Components/TextSpaceComponent.cpp
Library/src/Multiplayer/EventSerialisation.cpp
Library/src/Multiplayer/EventSerialisation.h
Library/src/Multiplayer/MultiplayerConnection.cpp
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Systems/Sequence/Sequence.cpp
Library/src/Systems/Sequence/SequenceSystem.cpp
Library/src/Systems/SystemsManager.cpp
Tests/src/PublicAPITests/ComponentTests/TextComponentTests.cpp
Tests/src/PublicAPITests/SequenceSystemTests.cpp

Commit contains:
- SequenceSystem
- Tests
- Multiplayer event
- Additional functions from: https://magnopus.atlassian.net/browse/OF-1340

[OF-1334] feat: Sequence System - Generic system for storing shared sorted lists.

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

[OF-596] refac: Replace `GetProfilesByUserId` with `GetBasicProfilesByUserId`

---

Library/include/CSP/Systems/Sequence/SequenceSystem.h

Documentation PR here: https://github.com/magnopus/olympus-specs/pull/28

[OF-1365] Updated inline docs for sequence key

---

Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp

- Added a test timeout to the loop to prevent hanging in the future

[OB-3664] Fixed CustomComponentTest from hanging

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/include/CSP/Multiplayer/Components/AnimatedModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ButtonSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ExternalLinkSpaceComponent.h
Library/include/CSP/Multiplayer/Components/FiducialMarkerSpaceComponent.h
Library/include/CSP/Multiplayer/Components/GaussianSplatSpaceComponent.h
Library/include/CSP/Multiplayer/Components/HotspotSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ImageSpaceComponent.h
Library/include/CSP/Multiplayer/Components/LightSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ReflectionSpaceComponent.h
Library/include/CSP/Multiplayer/Components/StaticModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/VideoPlayerSpaceComponent.h
Library/src/Multiplayer/ComponentBase.cpp
Library/src/Multiplayer/ComponentBaseKeys.h
Library/src/Multiplayer/Components/ExternalLinkSpaceComponent.cpp
Library/src/Multiplayer/Components/FiducialMarkerSpaceComponent.cpp
Library/src/Multiplayer/Components/HotspotSpaceComponent.cpp
Library/src/Multiplayer/Components/ImageSpaceComponent.cpp
Library/src/Multiplayer/Components/ReflectionSpaceComponent.cpp
Library/src/Multiplayer/Components/VideoPlayerSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.h
Tests/src/InternalTests/SerialisationTests.cpp
Tests/src/PublicAPITests/ComponentTests/ComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp

- Added GetComponentName and SetComponentName to ComponentBase
- Deprecated Name properties and accessors on derived classes
- Setup script accessor for aname
- Added tests for name in ComponentBase

[OF-1313] feat: Add name property to component base

---

Library/include/CSP/Systems/Sequence/Sequence.h
Library/src/Systems/Sequence/SequenceSystem.cpp
Tests/src/TestHelpers.h

Merged main (14 commits ahead) into branch to sync with develop.

Fix main develop async

---

Library/src/Multiplayer/SpaceEntity.cpp

* updated SpaceEntity.cpp to use c_str instead of string

[NT-0] fix: fix android failure error

---

Examples/Basic Framework/Web/index.js
Examples/Basic Framework/Web/package.json
Examples/Basic Framework/Web/yarn.lock
Examples/Initialising Foundation/Web/index.js
Examples/Initialising Foundation/Web/package.json
Examples/Initialising Foundation/Web/yarn.lock

[OW-1812] feat: Update endpoint used by web examples
- Updated endpoint for web examples
- Updated web examples to CSP 5.1.0
[OW-1812]: https://magnopus.atlassian.net/browse/OW-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OW-1812] feat: Update endpoint used by web examples

---

Examples/Basic Framework/CPlusPlus/BasicFramework/BasicFramework/BasicFramework.cpp
Examples/Initialising Foundation/CPlusPlus/InitialisingFoundation/InitialisingFoundation/InitialisingFoundation.cpp
Examples/Multiplayer/CSharp/Csp-Unity-VisionPro-Example/Assets/Scripts/HelloWorld.cs
Examples/Multiplayer/CSharp/Csp-Unity-VisionPro-Example/Packages/manifest.json
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Assets/Scripts/HelloWorld.cs
Examples/Multiplayer/CSharp/Foundation-Unity-Example/Packages/manifest.json

Misc/NT-0 : Update Example Project URLs & CSP version

---

Library/include/CSP/Systems/Users/Authentication.h
Library/src/Systems/Users/UserSystem.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

[OF-1420] refac: Add ReferenceID to Agora token

---

Tests/src/PublicAPITests/HotspotSequenceTests.cpp

Since the order of multiplayer events is not guaranteed, these checks can fail if the order does not come through in the way the tests expect.
We plan to add additional logic to CSP to make the events always appear to come through in a reliable order in the future, but for we're disabling these checks to avoid flakey behavior.

[NT-0] test: Disabling hotspot group event validation in tests

---

.gitignore
ThirdParty/quickjs/src/quickjs.c
generate_solution.bat

The premake scripts responsible for generating Visual Studio solutions now generate VS2022 solutions by default.

[NT-0] refac: CSP VS solutions now target VS2022 

---

Library/src/Json/JsonSerializer.cpp
Library/src/Json/JsonSerializer.h
Tests/src/InternalTests/JsonTests.cpp

- Added support for templated serialization/deserialization to easily serialize objects without modifying existing json code
- Added tests for current features.

[OF-1438] Templated Json Serializer

---

.gitmodules

chevron is already in requirements.txt so submodule is unused

[nt-0] refac: remove unnecessary chevron submodule

---

Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/Sequence/SequenceSystem.cpp

Updated to the latest CHS release version: 2.0-d20241031.rea46ffd36.Release

[NT-0] refac: Update CHS release version

---

teamcity/BuildWindowsPackage.py

Add a new BuildWindowsPackage script to package the Win64 lib and include files for a CSP Feature build.

[NT-0] feat: Add Windows package script

---

Library/include/CSP/Systems/Settings/SettingsCollection.h
Library/src/Systems/Settings/SettingsCollection.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Tests/src/PublicAPITests/SettingsSystemTests.cpp

- Updated AvatarInfoResult to use a string
- updated relevant tests

[OF-1408] fix: update AvatarInfoResult type

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/include/CSP/Multiplayer/ReplicatedValue.h
Library/src/Multiplayer/ComponentBase.cpp
Library/src/Multiplayer/Components/AnimatedModelSpaceComponent.cpp
Library/src/Multiplayer/Components/StaticModelSpaceComponent.cpp
Library/src/Multiplayer/MultiplayerConstants.h
Library/src/Multiplayer/ReplicatedValue.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.cpp
Tests/src/InternalTests/SerialisationTests.cpp
Tests/src/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp
Tests/src/PublicAPITests/ReplicatedValueTests2.cpp

* Update custom map to use supported string map
* Added tests to ensure CHS correctly supports this type

[OF-1519] fix: replicated map

---

Library/include/CSP/Multiplayer/EventParameters.h
Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/src/Multiplayer/MultiplayerConnection.cpp
Tests/src/PublicAPITests/MaterialTests.cpp

* Added a Material changed event which uses the existing AssetDetailBlobChanged event
* Added tests to verify behaviour

[OF-1518] feat: Add material changed event

---

Library/docs/source/_static/mcs/aggregation_service.png
Library/docs/source/_static/mcs/asset_service.png
Library/docs/source/_static/mcs/multiplayer_service.png
Library/docs/source/_static/mcs/ranking_service.png
Library/docs/source/_static/mcs/spatialdata_service.png
Library/docs/source/_static/mcs/user_service.png
Library/docs/source/_static/physical_digital/gca_flow.png
Library/docs/source/_static/tenants/tenant_flow_csp.png

Updated various diagrams throughout the documentation with a new visual treatment.

[NT-0] doc: visual treatment for diagrams

---

Library/src/Multiplayer/MultiplayerConnection.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp

- Added connection callback in StartListening callback to ensure its called on the main thread in wasm
- Added test

[NT-0] fix: add connected callback

---

Tests/src/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp

- Removing tests that fail on public TC server

[NT-0] test: remove model component tests

---

Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/src/Systems/Spaces/SpaceSystem.cpp

Fix typo, "Neccesary -> Necessary".
Came up in a log message, so technically external behaviour.
https://magnopus.slack.com/archives/C037VC209QT/p1740656900936649
@MAG-DanielMurdolo

[NT-0] chore: Necessary typo

---

Library/include/CSP/Multiplayer/Components/ConversationSpaceComponent.h
Library/include/CSP/Multiplayer/Conversation/Conversation.h
Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Library/src/Systems/Conversation/ConversationSystemInternal.cpp
Library/src/Systems/Conversation/ConversationSystemInternal.h
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

- Updated the following method names:
- SetMessageInfo ->UpdateMessage
- SetConversation Info -> UpdateConversation
- Added new structure to update the requires message params
- Updates tests to work with the new system

[OF-1567] feat: Create new methods for editing conversations

---

Library/include/CSP/Multiplayer/Conversation/Conversation.h
Library/src/Common/DateTime.cpp
Library/src/Common/DateTime.h
Library/src/Systems/Conversation/ConversationSystemInternal.cpp
Library/src/Systems/Conversation/ConversationSystemInternal.h
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp
Tests/src/PublicAPITests/ConversationSystemTests.cpp
Tests/src/PublicAPITests/DateTimeTests.cpp

- Added UTC timestamp to internal DateTime class
- Created/Edited timestamps are now added to conversations internally
- Tests have been added

[OF-1568] feat: Populate timestamps internally

---

Library/src/ExplicitTypes.cpp

Prevent unresolved externals for Array<GLTFMaterial>

[NT-0] fix: export gltf material array

---

Library/include/CSP/Multiplayer/Components/ConversationSpaceComponent.h
Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/ConversationSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/ConversationSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

- Added missing CameraRotation property
- Added script interface for new property
- Updated tests to verify its working.

[OF-1593] fix: Add missing property

---

Library/include/CSP/Systems/Users/Profile.h
Library/src/Systems/Users/Profile.cpp

This wasn't used by anyone, and was confusing people.
From low hanging fruit session

[OF-909] chore: Remove lastplatform from BasicProfile

---

Tests/src/PublicAPITests/CancellationTokenTests.cpp
Tests/src/PublicAPITests/ComponentTests/AudioComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CinematicCameraComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CollisionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ECommerceComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FiducialMarkerComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FogComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/GaussianSplatComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ImageComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LightComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LinkComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/PortalComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ReflectionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/SplineComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/TextComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/VideoPlayerComponentTests.cpp
Tests/src/PublicAPITests/ECommerceSystemTests.cpp
Tests/src/PublicAPITests/MaintenanceSystemTests.cpp
Tests/src/PublicAPITests/ScriptSystemTests.cpp
Tests/src/PublicAPITests/SystemResultTests.cpp

Put all the tests under CSPEngine or DISABLED_CSPEngine.
Before:
After:

[NT-0] chore: put all tests under CSPEngine or DISABLED_CSPEngine

---

Library/src/Common/Continuations.h

Added changes to support templated type in continuations as well as default scheduler based of off @MAG-mv changes on OF-1386-annotations

[NT-0] refac: extend continuation to support templates and default scheduler

---

.github/README.md

Update links to new main branch, `main`, away from old main branch `Main`

[OB-4276] doc: Update readme links

---

Library/include/CSP/Multiplayer/Components/ConversationSpaceComponent.h
Library/include/CSP/Multiplayer/Conversation/Conversation.h
Library/src/Multiplayer/Conversation/Conversation.cpp
Library/src/Systems/Conversation/ConversationSystemHelpers.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

- Changed FOV to double
- Added CSP_ASYNC_RESULT macro to GetAnnotationThumbnailsForConversation
- Removed setters and getters from AnnotationData
- Updated tests

[NT-0] feat: annotation fixes

---

.github/workflows/codeql.yml

Aiden has a ticket to figure out the point of these, but they're busted, so don't trigger them.

[NT-0] test: Disable the codeQL jobs

---

Library/src/Systems/Spaces/SpaceSystem.cpp

Update CHS wrapper to 2.0-d20250604.r243626491.Release+1

[NT-0] chore: Update CHS wrapper to 2.0-d20250604.r243626491.Release

---

WasmTesting/csp-wasm.test.ts
WasmTesting/html_tests/EnterSpace.html
WasmTesting/testhelpers.ts

From a low hanging fruit session, add a rough & ready test for entering a space. Running this on CI is going to catch so many things, it more than doubles our automated WASM coverage, heh.

[OF-1677] test: Add enter space HTML test

---

Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

The log is incorrect, fix it to make sense.
Came up from another PR: https://github.com/magnopus-opensource/connected-spaces-platform/pull/716#discussion_r2151649615

[NT-0] chore: Fix conversation space component log

---

UnitTesting/tests/RunUnityTests.py

This PR attempts to upgrade the Unity version for the run Unity Tests script to assess compatibility with Unity 6.

[OPE-2480] Ensure csp builds for unity 6

---

Library/include/CSP/Multiplayer/ComponentBase.h
Library/include/CSP/Multiplayer/Components/ScreenSharingSpaceComponent.h
Library/src/Multiplayer/Components/ScreenSharingSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/ScreenSharingSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/ScreenSharingSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Tests/src/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/AudioComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CinematicCameraComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CollisionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ECommerceComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FiducialMarkerComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/FogComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/GaussianSplatComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ImageComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LightComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/LinkComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ReflectionComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/ScreenSharingComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/SplineComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/TextComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/VideoPlayerComponentTests.cpp

Added a new Screen Sharing component which is designed to facilitate the sharing of a user's screen within a connected space.
Added tests to ensure the component can be constructed and updated correctly, as well as to ensure component property script bindings work correctly.
**Note for the reviewer:** While I was working on the new component tests, I noticed a couple of minor issues with our existing component tests, namely inconsistent test space creation and some erroneous comments. While I was in the area I elected to resolve these issues which is why there are so many file changes. This PR has two commits: Commit 1 has all of the changes required to add the new Screen Sharing component and it's tests. Commit 2 has all of the existing component updates. It is worth reviewing this PR by …

[OF-1730] feat: Added new Screen Sharing component
