magnopus-opensource/connected-spaces-platform

README.md

Making the repo public has broken all GitHub-hosted assets that we've uploaded. Fixing this first and most important one by reuploading the gif again.
I also took the liberty of removing the WIP section of the readme, as the page it links to is empty. We can revive it when content exists there.

[NT-0] doc: reuploaded readme gif

---

Library/include/CSP/Systems/EventTicketing/EventTicketingSystem.h
Library/src/CSP/Systems/EventTicketing/EventTicketing.cpp
Library/src/CSP/Systems/EventTicketing/EventTicketingSystem.cpp
Tests/CSharp/src/Tests/EventTicketingSystemTests.cs
Tests/src/PublicAPITests/EventTicketingSystemTests.cpp

Add functionality to EventTicketingSystem to enable updating ticketed events to change the third party vendor details and whether ticketing is active for the event.

[OF-1073] feat: Adds Update to EventTicketing

---

Library/include/CSP/Systems/EventTicketing/EventTicketing.h
Library/include/CSP/Systems/EventTicketing/EventTicketingSystem.h
Library/src/CSP/Systems/EventTicketing/EventTicketingSystem.cpp
Tests/src/PublicAPITests/EventTicketingSystemTests.cpp

CSP seeks to adopt American English. Updating the term 'authorise' to 'authorize' within the event ticketing API accordingly.

[OF-1078] fix: spelling correction

---

Library/src/CSPFoundation.cpp
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache

String copies were incorrectly pairing `CSP_NEW` with `DllFree` in the C interface, which was causing OOB errors when freeing strings returned from to any of our wrappers.

[OB-2795] fix: properly allocate and free strings

---

Library/include/CSP/Common/StringFormat.h
Library/src/CSPFoundation.cpp
Tests/src/InternalTests/CommonTypeTests/StringFormat.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache

We're looking to cut a new release of CSP, primarily to immediately address an issue found and fixed by @MAG-MichaelK over in https://github.com/magnopus-opensource/connected-spaces-platform/pull/107, where strings were being incorrectly deallocated.
There's one other change coming along for the ride, but it purely relates to tests, so no impact on the CSP binaries themselves.

CSP 4.5.1 - prepping a patch version to address a deallocator issue found in CSP

---

Library/include/CSP/Common/StringFormat.h
Library/src/CSPFoundation.cpp
Tests/src/InternalTests/CommonTypeTests/StringFormat.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tools/WrapperGenerator/Templates/C/Partials/Class/Method/Method.mustache

Part two of the release process, merging stage->main.
We're looking to cut a new release of CSP, primarily to immediately address an issue found and fixed by @MAG-MichaelK over in https://github.com/magnopus-opensource/connected-spaces-platform/pull/107, where strings were being incorrectly deallocated.
There's one other change coming along for the ride, but it purely relates to tests, so no impact on the CSP binaries themselves.

CSP 4.5.1 - patch version changes to address a deallocator issue found in CSP 

---

Library/src/Web/HttpPayload.cpp
Library/src/Web/HttpPayload.h
Library/src/Web/WebClient.cpp
Tests/src/PublicAPITests/GraphQLSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

This adds a function to HttpPayload to check if the payload has a JSON mime-type. This is then used when printing error messages to check if an error response is JSON formatted before trying to parse it as JSON. If it is not JSON then it is simply printed as is.

[OB-2804] fix: Handle non-JSON error responses

---

Library/include/CSP/Common/List.h
Library/include/CSP/Common/String.h
Library/include/CSP/Systems/Assets/Asset.h
Library/src/Common/String.cpp
Library/src/Multiplayer/SignalR/SignalRClient.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Services/ApiBase/ApiBase.cpp
Library/src/Services/ApiBase/ApiBase.h
Library/src/Systems/Analytics/AnalyticsProviderGoogleUA.cpp
Library/src/Systems/Assets/Asset.cpp
Library/src/Web/EmscriptenWebClient/EmscriptenWebClient.cpp
Library/src/Web/HttpRequest.cpp
Library/src/Web/HttpRequest.h
Library/src/Web/HttpResponse.h
Library/src/Web/POCOWebClient/POCOWebClient.cpp
Library/src/Web/WebClient.cpp
Tests/Web/html/index.js
Tests/Web/html/olympus_foundation.js
Tests/Web/html/package.json
Tests/Web/html/tests/settingssystem_tests.js
Tests/src/InternalTests/SpaceHelperTests.cpp
Tests/src/InternalTests/WebClientTests.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp
Tools/WrapperGenerator/Templates/C/GeneratedWrapper.mustache

* Add `String` move ctor/op, and fix copy ctor/op
* `AssetDataResult` now uses underlying `ResponseBody` property instead of making a copy of the data.
* `UriResult` no longer copies headers when trying to read a single header value.
* Updated Web tests to use CSP 4.5.1
* Fixed CSP for Web paths in Web tests

[NT-0] fix: address stability issues

---

README.md

Updating language used to describe tenant keys to be tenant IDs on the readme, at the request of our services team. We're also making the same change on the website.

[NT-0] doc: changing tenant language from key to ID

---

README.md

We're now referring to tenant IDs as opposed to tenant keys. Found and updated another instance in the README with this in mind.

[NT-0] doc: corrected a reference to tenant IDs

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/UserSystem.cpp
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/UserSystemTests.cpp

Expose parameter for reset password to define whether link in Email should direct to token change URL.

[OB-2864] fix: Expose parameter for reset password

---

Library/include/CSP/Multiplayer/MultiPlayerConnection.h

There was a mismatch in the values for the `ChangeType` used in the `AssetDetailBlobChanged` event between CSP and and the Magnopus Cloud Services. 
CSP used the `EAssetChangeType` enum ordered as follows:
```
{
Created,
Updated,
Deleted,
MusubiFailed,
Invalid
};
```
Whereas the equivalent returned by Magnopus Cloud Services is ordered:
```
{
Created,
Updated,
MusubiFailed,
Deleted,
Invalid
};
```
(Notice that the `Deleted` and `MusubiFailed` values are inverted).
This meant that clients were receiving `AssetDetailBlobChanged` events with a change type of `MusubiFailed` when an asset had been deleted and vice-versa when Musubi processing failed.
This change updates the `EAssetChangeType` to match the Magnopus Cloud Services equivalent.

[OB-2914] fix: Fixed incorrect ordering in EAssetChangeType enum values for AssetDetailBlobChanged event

---

Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/include/CSP/Systems/Spaces/UserRoles.h
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/CSharp/src/Tests/ConversationSystemTests.cs
Tests/CSharp/src/Tests/MultiplayerTests.cs
Tests/CSharp/src/Tests/SpaceSystemTests.cs
Tests/Web/html/tests/spacesystem_tests.js
Tests/Web/html/tests/spacesystem_tests_helpers.js
Tests/src/PublicAPITests/ConversationSystemTests.cpp
Tests/src/PublicAPITests/SpaceSystemTestHelpers.h
Tests/src/PublicAPITests/SpaceSystemTests.cpp

This changes when there is an array of InviteUserRoleInfo to use a new InviteUserRoleInfoCollection. This collection class now includes an EmailLinkUrl parameter that can be provided to specify where to redirect a user back to. It is OK to leave this blank. This applies to the CreateSpace, CreateSpaceWithBuffer and BulkInviteToSpace calls.
The same thing is also added as a new optional parameter to the InviteToSpace call.

[OF-1151] feat!: Add email link for user invite

---

Library/include/CSP/Multiplayer/MultiPlayerConnection.h

Remove redundant deprecation warnings from MultiplayerConnection.

[OF-1156] fix: Remove deprecation warnings

---

Library/include/CSP/Multiplayer/Components/AnimatedModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/ExternalLinkSpaceComponent.h
Library/include/CSP/Multiplayer/Components/StaticModelSpaceComponent.h

All CSP multiplayer components now declare functions with `override` when overriding interface functions.
This prevents compile-time warnings from being emitted in C++ client applications that reference these functions.

[OB-2474] fix: C++ compile warnings

---

Library/include/CSP/Services/WebService.h
Library/include/CSP/Systems/Users/Authentication.h
Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Services/WebService.cpp
Library/src/Systems/Users/Authentication.cpp
Library/src/Systems/Users/UserSystem.cpp
Tests/CSharp/src/ExtensionMethods.cs
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/Multiplayer/src/MultiplayerTestClient.cs
Tests/src/PublicAPITests/UserSystemTests.cpp

This change adds `HasVerifiedAge` to `CreateUser` and `Login` functions. It also adds a way of getting back errors returned by CHS via the `X-ErrorCode` response header.

[OF-1119] feat: add age verification flag

---

Library/src/Multiplayer/Script/EntityScriptBinding.cpp

A client engineer observed that log messages emitted via script were being assigned the 'Error' verbosity level, which was unexpected.
It was agreed that the expected level is the regular 'Log' level.

[NT-0] fix: script logs use log verbosity level

---

teamcity/templates/unity/minimal.meta.jinja2
teamcity/templates/unity/plugin.meta.jinja2
teamcity/templates/unity/source.cs.meta.jinja2

This fixes an issue with CSP for Unity iOS referencing null.framework

[NT-0] fix: Fix unity package meta templates

---

requirements.txt

Python 3.10 and above currently has issues with PyYAML versions 5.4 and above. More info [here](https://github.com/galaxyproject/iwc/pull/226). Adopting the recommended workaround and targeting PyYAML 5.3.1 instead.

[NT-0] fix: change required PyYAML version

---

Library/src/Common/String.cpp

This addresses an issue that occurs when trying to reassign a string value that hasn't been initialised where the underlying StringImpl is deleted, even though it is null. This happens with ReplicatedValue and Variant.

[OB-2980] fix: only delete StringImpl if not null

---

Library/docs/source/index.md

The landing page for the API docs now refers to the fact that CSP packages are now hosted on `npmjs` rather than GitHub.

[NT-0] doc: API docs package references

---

Library/include/CSP/Systems/Quota/QuotaSystem.h
Library/src/Systems/Quota/QuotaSystem.cpp

A bug in the CSP wrapper generator means that reference-to-enum parameters will be considered to be int pointers at the C# wrapper level.
These int pointers were then passed to the generated C wrapper, which attempted to dereference them before passing them to CSP's C++ API.
Those dereferences were the cause of the crash.
The fix here is to alter the signature of the QuotaSystem API such that it passes enum params by value rather than reference.
A separate issue for the wrapper generator bug will be raised and tracked.

[OB-3040] fix: Resolving a QuotaSystem C# crash

---

Library/src/Systems/Quota/Quota.cpp
Tests/src/PublicAPITests/QuotaSystemTests.cpp

We had a typo in the strings we created to form URL GET requests, where we were creating tier strings that began with an uppercase.
The convention here is for tier strings to be all lowercase.
The impact was that services could return 200 responses to the incorrectly formatted GET requests but with the wrong information.
And the fix is to ensure tier string parsing is consistently treating the tier names as all lower-case.

[OB-3042] fix: quota queries for non-basic tiers

---

generate_solution_ios.sh
generate_solution_mac.sh

In the same way we automatically install python dependencies at the start of the project generation process on Windows, we now also invoke the equivalent pip command at the start of OSX project generation.

[NT-0] feat: Dependencies auto-install on OSX

---

Library/include/CSP/Common/CancellationToken.h
Library/src/Common/CancellationToken.cpp
Tests/src/PublicAPITests/CancellationTokenTests.cpp

Introducing test coverage for `csp::common::CancellationToken`.

[OF-1094] test: Cancellation token tests

---

.clang-format

Our .clangformat file had a duplicate entry, causing newer versions of clangformat to throw an error.

[NT-0] fix: fix .clangformat for latest clang ver

---

Library/include/CSP/Common/String.h
Library/src/Common/String.cpp
Library/src/Web/EmscriptenWebClient/EmscriptenWebClient.cpp
Tests/src/InternalTests/CommonTypeTests/String.cpp

This change removes an extra allocation in the code that transforms header keys and values to lower-case in `EmscriptenWebClient`. To support this, a new `String::ToLower` function was added which returns a copy of the string converted to lower-case.

[OF-1166] refac: optimise header transform

---

Library/include/CSP/CSPFoundation.h
Library/src/CSPFoundation.cpp

This API variable still exists from an old versioning pass which has been removed.
While we do want to do this versioning style in future, we are removing this from the code base now to prevent confusion down the line.

[OF-955] refac: removing `EntitySystemVersion`

---

generate_solution.bat

On windows, the python prerequisites installed during at the start of solution generation now invokes the same python commands as on OSX.

[NT-0] fix: python preq installation

---

Library/include/CSP/Systems/Settings/SettingsCollection.h
Library/include/CSP/Systems/Settings/SettingsSystem.h
Library/src/Systems/Settings/SettingsCollection.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Library/src/Systems/Spaces/Space.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Library/src/Systems/Spaces/SpaceSystemHelpers.cpp
Library/src/Systems/Spaces/SpaceSystemHelpers.h
Tests/src/InternalTests/SpaceHelperTests.cpp
Tests/src/PublicAPITests/SettingsSystemTests.cpp

This change adds `SettingsSystem::SetAvatarInfo()` and `SettingsSystem::GetAvatarInfo()` to allow clients to set persistent Avatar values that can be retrieved outside of the Multiplayer system.

[OF-793] feat: add Avatar info settings

---

teamcity/requirements.txt

We have a python dependency on the distutils module. This module is missing on the uk-hw-win-01 agent, and so I am adding it to our requirements.txt file.

[NT-0] fix: Update module dependencies

---

teamcity/BuildNPMWebPackage.py
teamcity/PublishCSPForUnity.py

The build agents have been updated to Python 3.12
and support distutils has been removed with that release. Updating the script to use shutil.copy_tree instead.

[NT-0] fix: Remove distutils dependency

---

Library/src/Common/DateTime.h

The `DateTime` constructor that accepts a string argument now includes inline comments that document the expected format of the string being passed in.

[OF-1103] doc: DateTime string constructor inline documentation

---

Library/src/Web/POCOWebClient/POCOWebClient.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

* Fixed a crash when a bad path was supplied for a file upload
* Added a test for bad paths in uploads

[OB-953] fix: FileAssetDataSource bad path

---

.clang-format
Library/include/CSP/Systems/SystemsResult.h
Library/include/CSP/Systems/Users/Authentication.h
Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/Authentication.cpp
Library/src/Systems/Users/Authentication.h
Library/src/Systems/Users/UserSystem.cpp
Tests/CSharp/src/Tests/UserSystemTests.cs
Tests/src/PublicAPITests/UserSystemTests.cpp

Some result types have been refactored to reduce the number of public result types, and to make the return value type more apparent.
BREAKING CHANGES:
* `UserSystem::LogOut` now takes `NullResultCallback` instead of `LogoutResultCallback`. `LogoutResultCallback` is now private.
* `UserSystem::GetAgoraUserToken` now takes `StringResultCallback` instead of `UserTokenResultCallback`. `UserTokenResultCallback` is now private.
* `UserSystem::GetCustomerPortalUrl` now takes `StringResultCallback` instead of `CustomerPortalUrlResultCallback`. `CustomerPortalUrlResultCallback` is now private.
* `UserSystem::GetCheckoutSessionUrl` now takes `StringResultCallback` instead of `CheckoutSessionUrlResultCallback`. `CheckoutSessionUrlResultCallback` is now private.
* `UserSystem::Ping` now takes a …

[NT-0] refac!: Refactor Authentication results

---

Library/include/CSP/Systems/Assets/AssetSystem.h
Library/src/Multiplayer/Conversation/ConversationSystem.cpp
Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/CSharp/src/Tests/AssetSystemTests.cs
Tests/src/PublicAPITests/AssetSystemTests.cpp

This change merges `GetAssetCollectionsById` and
`GetAssetCollectionsByCriteria` into the function
`FindAssetCollections`

[OF-498] refac!: merge asset collection get functions

---

Library/include/CSP/Common/Map.h

Indexing into a const `Map` with a key that is not already present will no longer cause an allocation and will instead throw.

[OB-3073] fix: ensure const `Map` is immutable

---

Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/include/CSP/Systems/Analytics/AnalyticsSystem.h
Library/include/CSP/Systems/Assets/AssetSystem.h
Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/include/CSP/Systems/EventTicketing/EventTicketingSystem.h
Library/include/CSP/Systems/GraphQL/GraphQLSystem.h
Library/include/CSP/Systems/Log/LogSystem.h
Library/include/CSP/Systems/Maintenance/MaintenanceSystem.h
Library/include/CSP/Systems/Quota/QuotaSystem.h
Library/include/CSP/Systems/Script/ScriptSystem.h
Library/include/CSP/Systems/Settings/SettingsSystem.h
Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/include/CSP/Systems/Spatial/AnchorSystem.h
Library/include/CSP/Systems/Spatial/PointOfInterestSystem.h
Library/include/CSP/Systems/SystemsManager.h
Library/include/CSP/Systems/Users/UserSystem.h
Library/include/CSP/Systems/Voip/VoipSystem.h
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Tests/src/PublicAPITests/Analytics/AnalyticsSystemUnitTests.cpp
Tools/WrapperGenerator/Templates/CSharp/Partials/Class/Method/Destructor.mustache

BREAKING CHANGE: Systems classes no longer expose their destructors. If you were calling `delete` (C++), `.Dispose()` (C#), or `.delete()` (JS) you will need to remove these calls.

[OF-998] refac!: make Systems dtors private

---

Library/premake5.lua

`import.meta` is not yet supported everywhere, so disable it for now

[OF-1165] fix: disable import.meta in TS wrapper

---

Library/premake5.lua

This change reverts a previous change we made to disable usage of import.meta in the WASM glue code in order to improve compatibility with build tools. Disabling import.meta actually ended up breaking webpack, so away it goes.

[NT-0] fix: revert import.meta change

---

Library/src/Multiplayer/ComponentBase.cpp

Fixes an issue where we were passing a String instead of a C-String to CSP_LOG_*.

[NT-0] fix: logging arg fix

---

teamcity/GenerateReadMe.py
teamcity/templates/readme/readme.md.jinja2

This change fixes an issue where commit message parsing fails for commits authored from the GitHub UI, as no newline character exists. It also fixes an issue with summary lists breaking the string case of commit descriptions.

[NT-0] fix: fix readme gen for GH commits

---

Library/src/Multiplayer/Script/ComponentBinding/CustomSpaceComponentScriptInterface.cpp

This change fixes an issue where setting a new value on a property of a custom component in a script did not propagate that change to the clients.
- The function `CustomSpaceComponentScriptInterface::SetCustomProperty` was missing a call to `SendPropertyUpdate();` at the end. This was added.

[OB-3203] fix: fix SetCustomProperty not sending changes to clients

---

Library/src/Multiplayer/SpaceEntity.cpp

When an entity's properties cannot be mutated due to the local user not having permissions to change the values, CSP emits a log message which now includes the entity's name in the message.

[OF-687] fix: entity names emitted in log messages

---

Library/src/Multiplayer/Script/ComponentBinding/SplineSpaceComponentScriptInterface.cpp

This change fixes an issue with SplineSpaceComponentScriptInterface only returning a third of waypoints.

[OB-3227] fix: fix spline waypoints in script

---

Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Multiplayer/SpaceEntitySystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp

As part of a recent broad refactor to the multiplayer connection's application lifetime, the connection now persists for the duration of the application's lifetime. Entering a space now narrows the connections focus to listen to entities within the space, and exiting stops the connection from listening to entities within the space.
A bug has arisen however where whilst leaving a space stops the application receiving updates regarding entities, it does not clear CSP's local view of currently known entities.
This change introduces a new function to SpaceEntitySystem, `LocalDestroyAllEntities` which is invoked by the SpaceSystem after it has finished listening for entities within the space. It clear's CSP's local view of all currently known entities.
Tests have been updated to validate this …

[NT-0] fix: Local entities are destroyed upon exiting a space

---

Library/include/CSP/Multiplayer/Components/GaussianSplatSpaceComponent.h
Library/src/Multiplayer/Components/GaussianSplatSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/GaussianSplatSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/GaussianSplatSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Tests/src/PublicAPITests/ComponentTests/GaussianSplatComponentTests.cpp

The Gaussian Splat component now also describes a 'tint' property, which is intended to represent an RGB tuple that is globally applied to the Gaussian Splat asset associated with the component, when rendered in a client viewport.

[OF-1269] feat: Tint property for gaussian splats

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/src/Systems/ECommerce/ECommerce.cpp

CSP now default initializes all e-commerce structures' member variables to sensible values. It also reports additional errors to the log if expected values in DTOs returned by services are not present.
For more information, check out this [Slack thread](https://magnopus.slack.com/archives/C037VC209QT/p1712217718004689?thread_ts=1712161667.802179&cid=C037VC209QT).

[OB-3363] fix: e-commerce structures default values

---

Library/src/Systems/Users/UserSystem.cpp
Tools/OKOBuildTool/Src/OKOBuildTool.py

Discovered whilst debugging a client, when a client attempts to log out but does not have a valid MP connection, we emit an error message to the log. There was an error in the log formatting however, where it was expecting a string and being provided an int. 
This change fixes the formatting issue, and also includes some updates to the 'OKOBuildTool' - a legacy script that remains highly useful to this day as a workflow enhancer when debugging CSP issues in Unreal client applications. The updates concern naming and paths that have changed since the tool was last updated.

[NT-0] fix: Error log message formatting on failure to disconnect when logging out

---

Library/src/Multiplayer/SpaceEntity.cpp

[OB-3269] fix: Iterate over components correctly
- Fix issue in `SpaceEntity::FindFirstComponentOfType` which would only work correctly if a component had not been deleted from the entity
- The code was updated to iterate over the maps in question in a way consistent with other similar use cases in this class
- STL style iterators were added to the Map class as part of the TravelZoo work in this [PR](https://github.com/magnopus/connected-spaces-platform-internal/pull/4)
- These would probably be the best way to iterate over maps going forward
[OB-3269]: https://magnopus.atlassian.net/browse/OB-3269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OB-3269] fix: Iterate over components correctly

---

teamcity/templates/unity/plugin.meta.jinja2

This change should allow users of the Unity CSP package to run CSP within a Unity Editor Apple Silicon versions. Previously this was only possible for Unity Editor Intel versions.
This is what the change will look like on the macOS library's metadata.
Before:
After:
Tested locally by modifying metadata settings in-editor.
Now CSP appears to work as expected when running on a Unity client in both scenarios:
- CSP running on Unity Editor Intel (via Rosetta) as before
- CSP running on Unity Editor Apple Silicon
If there is a way to test the TC build scripts locally as well, please let me know. Thank you.

[NT-0] refac: Enable macOS binaries for Unity Editor Apple Silicon

---

Library/include/CSP/Systems/EventTicketing/EventTicketingSystem.h
Library/src/Systems/EventTicketing/EventTicketingSystem.cpp

This change makes most of the parameters for UpdateTicketedEvent optional, allowing devs to disable an event without providing all event parameters.

[OF-1176] refac: Make params in UpdateEvent opt

---

Tests/src/PublicAPITests/OrganizationSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTestHelpers.h
Tests/src/PublicAPITests/UserSystemTests.cpp

I have made the following quality of life improvements to remove the requirement to create/add new org test accounts to the test_account_creds.txt file: 
- I have reverted the test_account_creds.txt so that it only requires the default and alt email address and password information.
- I have reduced the Organization test account requirements down to a single test account with the member and admin roles.
- I have introduced a new organization_test_account_creds.txt file which contains the credentials for this new test account.
- I have updated the Functional Test TeamCity deployment steps to account for this.

[NT-0] refac: Refactor Org test accounts

---

Library/include/CSP/Systems/ECommerce/ECommerceSystem.h
Library/src/Systems/ECommerce/ECommerceSystem.cpp
Tests/src/PublicAPITests/ECommerceSystemTests.cpp

[OF-1302] refac: Remove UserID parameter from GetShopifyStores
- Update the GetShopifyStores to get the UserId from the internal UserSystem rather than as a parameter on the function, as we currently only want to get the current user's stores.
[OF-1302]: https://magnopus.atlassian.net/browse/OF-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OF-1302] refac: Remove UserID parameter from GetShopifyStores

---

Library/src/Multiplayer/Script/EntityScriptInterface.cpp
Library/src/Multiplayer/Script/EntityScriptInterface.h

[OB-3426] fix: Fix crash accessing components from scripts after component removed
- Fix the way the component list is iterated over in 
- `EntityScriptInterface::GetComponents()` 
- `EntityScriptInterface::GetComponentsOfType()`
[OB-3426]: https://magnopus.atlassian.net/browse/OB-3426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OB-3426] fix: Fix crash accessing components from scripts after component removed

---

Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Multiplayer/Election/ClientElectionManager.cpp
Library/src/Multiplayer/Election/ClientElectionManager.h
Library/src/Multiplayer/Script/EntityScript.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tools/WrapperGenerator/Parser.py

This change ensures that entities are deleted and leader election is reset when exiting a space.

[OB-3438] fix: ensure context clear on ExitSpace

---

Tools/WrapperGenerator/Templates/CSharp/Class.mustache

The C# wrapper generator was generating p/invoke imports for private constructors and destructors, resulting in VisionOS attempting to link against these non-existing exports.

[OB-3490] fix: don't p/invoke private ctors/dtors

---

generate_solution_ios.sh
generate_solution_mac.sh
generate_solution_visionos.sh

As of Python 3.12+ it is a requirement that we use a venv to install modules. The generate_solution_X.sh scripts for mac, ios and visionos have all been updated to check for the version of Python installed, and if >= 3.12, to create and activate a venv before proceeding with module installation.

[OF-1322] refac: Update generate shell scripts

---

Library/include/CSP/Common/Variant.h
Library/src/Common/Variant.cpp

This change expands floats in `csp::common::Variant` from single to double precision.

[NT-0] refac: expand `Variant` float type

---

Library/include/CSP/Systems/Organizations/Organization.h
Library/include/CSP/Systems/Organizations/OrganizationSystem.h
Library/src/Systems/Organizations/Organization.cpp
Library/src/Systems/Organizations/OrganizationSystem.cpp
Tests/src/PublicAPITests/ConversationSystemTests.cpp
Tests/src/PublicAPITests/OrganizationSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTestHelpers.h
Tests/src/PublicAPITests/UserSystemTests.cpp

Added support for CRUD endpoints to the Organization System so that users are able to Create, Get, Update and Deactivate Organizations. Tests have also been added to validate these new endpoints.
In addition the requirement for a separate Organization test account credentials text file has been removed, and the account credentials of the OKO_TESTS tenant admin are now read from the existing account credentials file.

[OF-1237] feat: Organization System support for CRUD endpoints

---

teamcity/templates/unity/NativePluginBuildProcessor.cs

This change addresses an issue that was found to be preventing the libConnectedSpacesPlatform.a binary from being included in XCode projects generated by Unity.
The cause was an omission in a CSP-provided Unity build script, where the logic that determines whether or not to include the binary was not accounting for the VisionOS platform.
Full kudos to @MAG-MichaelK for finding the bug & fix!

[OB-3568] fix: VisionOS Unity Build Script Failing to Include CSP Binaries

---

Tests/src/PublicAPITests/EventTicketingSystemTests.cpp

EventBrite have made a services change that now rejects data that does not match their expected schema.
We have addressed this in CSP tests by changing the data passed into CSP to match the EventBrite schema.
We have also refactored the eticketing tests to all rely on a single set of test variables, to simplify updates in the future.

[NT-0] test: Updating CSP tests to comply with new EventBrite data formatting requirements

---

Library/include/CSP/Systems/ECommerce/ECommerce.h
Library/src/Systems/ECommerce/ECommerceSystem.cpp

* GetCheckoutInformation checks CartId for forward and backward slashes, early outs if found
Unsure if this is the best approach, but wrapper gen changes for API level coverage were too complex to achieve in a reasonable time-frame. It's questionable if this is better than no change at all, so I expect discussion either here in PR or externally.

[OF-1324] fix: path validation for CartId

---

Library/include/CSP/Multiplayer/Components/HotspotSpaceComponent.h
Library/src/Multiplayer/Components/HotspotSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/HotspotSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/HotspotSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp

[OF-1359] refac: Update the hotspot component type properties
- Removed the hotspot space component get/set hotspot type methods and associated property
- Removed the enum for HotspotType
- Added get/set IsTeleportPoint and IsSpawnPoint methods both storing their values in boolean properties
- Updated the hotspot space component script interface
- Updated the hostspot space component tests
[OF-1359]: https://magnopus.atlassian.net/browse/OF-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OF-1359] refac: Update the hotspot component type properties

---

Library/src/Systems/SystemsManager.cpp

Systems must be shut down in reverse order to `CreateSystems()` to ensure that any dependencies continue to exist until each system is successfully shut down.
This resolves a potential crash on shutdown, as it prevents the script system from being deleted before script entities.
Found via a Unity client where CSP is shutdown when terminating a play session in-editor.

[OB-3650] fix: reverse shutdown order

---

Library/src/Multiplayer/MultiplayerConnection.cpp

Use the callback to block the thread until the disconnection is complete ensuring that any callbacks fired during the shutdown process are completely handled before the system is destroyed.

[OB-3653] fix: sync ~MultiplayerConnection()

---

Library/include/CSP/Systems/Spatial/PointOfInterest.h
Library/include/CSP/Systems/Spatial/PointOfInterestSystem.h
Library/src/Systems/Spatial/PointOfInterest.cpp
Library/src/Systems/Spatial/PointOfInterestHelpers.h
Library/src/Systems/Spatial/PointOfInterestInternalSystem.h
Library/src/Systems/Spatial/PointOfInterestSystem.cpp
Tests/CSharp/src/Tests/PointOfInterestSystemTests.cs
Tests/src/PublicAPITests/PointOfInterestSystemTests.cpp
Tests/src/TestHelpers.h

Discovered whilst writing spatial services documentation for CSP, there was a client-application-level feature missing, where whilst the client app is able to associate a POI with a space using the `UpdateSpaceGeoLocation` method on `SpaceSystem`, they had no affordance via the POISystem to later query for POIs associated with spaces.
In fact, the POISystem was deliberately filtering out POIs that were associated with spaces, and only ever returning `DEFAULT` type POIs.
This change introduces a new optional parameter to the POI System, `Type`, which allows the client to query for only POIs of a certain type. 
* If all types are desired to be included in the returned results, the optional value should not be specified.
* If the previous behaviour of CSP when returning results is preferred, …

[NT-0] feat: Querying for local POIs by type

---

Library/include/CSP/Systems/Sequence/Sequence.h
Library/include/CSP/Systems/Sequence/SequenceSystem.h
Library/src/Systems/Sequence/SequenceSystem.cpp
Tests/src/PublicAPITests/SequenceSystemTests.cpp
Tools/WrapperGenerator/CSharpWrapperGenerator.py

Updated Sequence result doxygen comments
Added ASYNC macro to sequence API
Removed optional constraint from API
updated sentinal check in SequenceSystem
Updated test to consume new API
Added better error reporting to wrapper gen

[OF-1378] fix: Add Async macros to API and remove optional parameter tags

---

Tests/src/PublicAPITests/UserSystemTests.cpp

This pull request will remove an un-used problematic test. No other changes, or code additions.

[OF-688] refac: Delete cancel login test

---

Library/CSharpWrapper/src/Constants.cs
Tools/WrapperGenerator/Templates/CSharp/Partials/DllImport.mustache

Small refactor that makes the generated C# code a little less verbose
- Moved conditional compilation into a constant
- Simplified template/generated code

refac: simplify dllimports

---

Library/include/CSP/Multiplayer/SequenceHierarchy.h
Library/include/CSP/Systems/Sequence/Sequence.h
Library/src/Multiplayer/EventSerialisation.cpp
Library/src/Multiplayer/MultiplayerConnection.cpp
Library/src/Multiplayer/MultiplayerConstants.cpp
Library/src/Multiplayer/MultiplayerConstants.h
Library/src/Multiplayer/NetworkEventManagerImpl.cpp
Library/src/Multiplayer/SequenceHierarchy.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.h
Library/src/Multiplayer/SpaceEntitySystem.cpp
Tests/src/PublicAPITests/SequenceHierarchyTests.cpp

This change concerns moving a static string declaration in the global scope out of a public header. Specifically `SequenceHierarchyName`.
Global variable strings within CSP can cause apps using CSP dlls to *crash on load* of the DLL, as it leads to the application attempting to instantiate the global-scope string variable on DLL-load, _before_ CSP has initialised its memory allocators, which the string class depends upon. The end result is a null dereference crash.
The fix though is to _not_ declare this string variable at the global scope, because this will always be risky with respect to CSP's memory allocators. Instead it is retrieved through a global-scope static function, which more or less guarantees that it will only ever be called after the allocators have been initialised.
Since …

[NT-0] fix: crash on DLL load for CPP apps

---

.github/pull_request_template.md

The previous check-box-oriented template was underutilized and frequently left unmodified upon merge.
Updating the template to be more of a call to action, in an effort to encourage contributors to include descriptive PR messages.

[NT-0] doc: updating PR template

---

Library/src/Common/Encode.cpp
Library/src/Common/Encode.h
Library/src/Multiplayer/EventSerialisation.cpp
Library/src/Systems/Sequence/Sequence.cpp
Library/src/Systems/Sequence/SequenceSystem.cpp
Library/src/Systems/WebService.cpp
Tests/src/InternalTests/EncodeTests.cpp
Tests/src/PublicAPITests/SequenceSystemTests.cpp

CSP client applications can now reason about sequence keys that include characters usually reserved in URIs, such as spaces.
As part of this work, we have introduced a new set of encoding source files for future encode/decode behaviour.
During development, we discovered that there are some service endpoints currently expecting the provided keys to be _doubly_ encoded. The current approach takes this into account and double-encodes where necessary from a services point of view.

[OF-1419] feat: hotspot names support the space character

---

Library/include/CSP/Multiplayer/Components/HotspotSpaceComponent.h
Library/src/Multiplayer/Components/HotspotSpaceComponent.cpp
Tests/src/PublicAPITests/ComponentTests/HotspotComponentTests.cpp

The function was returning a reference to a string local variable declared in the function.
Fixed by returning by value instead.

[NT-0] fix: hotspot unique ID accessor

---

.gitmodules

`modules/msgpack` and `modules/openssl` don't have corresponding `gitlink`s so their entries in `.gitmodules` are incorrect
Further discussion in [this Slack thread](https://magnopus.slack.com/archives/C037VC209QT/p1728074303456579)

[nt-0] fix: remove missing submodules

---

teamcity/GenerateReadMeWithLink.py

Rather than generating package release notes for upload to npmjs, we will instead be directing people to view the Release Notes on the CSP open source repo.

[NT-0] feat: Update package release notes

---

Library/include/CSP/Multiplayer/Components/CinematicCameraSpaceComponent.h

[OSB-11] fix: Added missing override specifier for Cinematic Camera component methods
- The methods in the `CinematicCameraSpaceComponent` class that override those from the `IEnableableComponent` interface were missing the `override` specifier, causing a compiler warning
[OSB-11]: https://magnopus.atlassian.net/browse/OSB-11?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OSB-11] fix: Added missing override specifier for Cinematic Camera component methods

---

.githooks/commit-msg

Replaced some nasty bash scripting with a single regex.
* Checker also allows Github ticket IDs now, i.e. `[#1234] refac: lorem ipsum dolor`
* Failing the ticket ID check will report a meaningful error message instead of nagging you about verbs.

[nt-0] fix: validate ticket ID with single regex

---

.github/README.md

Something I noticed whilst browsing for getting started examples.
Links to the getting started examples were outdated, and hitting 404's, presumably from a prior branch name switch from main -> develop.

Reseat example links from main -> develop branch

---

teamcity/PublishCSPForUnity.py

Updated the default type of an argument to be a string so that is can be correctly evaluated.
This argument is evaluated to a bool as it will be a string by default when passed in. This means the default value must also be a string.

[NT-0] fix: Update the Unity publish script

---

teamcity/PublishCSPForUnity.py

A change to one of the TeamCity Unity publish build scripts was required to ensure that a script argument is correctly evaluated.

CSP 5.4.0 - fix to build script required.

---

Library/src/Multiplayer/Components/CinematicCameraSpaceComponent.cpp
Tests/src/PublicAPITests/ComponentTests/CinematicCameraComponentTests.cpp

[OF-1459] fix: update cinematic camera GetFov() to match aspect ratio
- updated CinematicCameraSpaceComponent GetFov() calculation to take aspect ratio into account
- updated unit tests
[OF-1459]: https://magnopus.atlassian.net/browse/OF-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OF-1459] fix: update cinematic camera GetFov() to match aspect ratio

---

Tests/src/PublicAPITests/AssetSystemTests.cpp

This test is broken due to a presumed change in CHS. We are disabling it to unblock other PRs.
Ticket linked in the title is the ticket to re-enable.

[OF-1477] test: Disable CopyAssetCollectionTest

---

Library/src/Systems/Assets/Asset.cpp
Tests/assets/TestWith Space.json
Tests/assets/TestWithEncoded%20Space.json
Tests/src/PublicAPITests/AssetSystemTests.cpp

CSP made a change in March to encode URLs in asset details. We added this encode earlier than that to workaround the issue for a client team, but now it's causing double encode errors, so we should remove it.
Added a couple of tests so we'd know if this changes again.
(Magnopus slack confirming this change : https://magnopus.slack.com/archives/C02T07E8P2B/p1732097572110679)

[OB-3674] fix: Do not encode already encoded URLs

---

Library/include/CSP/Systems/Settings/SettingsCollection.h

Fix initializer list ordering for GetAvatarIdentifier. This was surfacing on mac builds. The CI should be enough to prove this is fine.
It's odd that only this warning was surfacing, as there's lots of warnings of the same nature if you enable
all the warnings. What's odder is that I couldn't get _this specific_ warning to trigger on Windows, despite being able
to see loads of other bad ordering.
Although, this is perhaps a little different in that it's in a header, and external warnings are treated differently to internal ones, and I know GCC/Apple-clang defaults around this are different to MSVC. Could be what caused this to be seen and not others

[OSB-12] fix: Init order AvatarInfoResult

---

Library/include/CSP/Multiplayer/Components/AnimatedModelSpaceComponent.h
Library/include/CSP/Multiplayer/Components/StaticModelSpaceComponent.h
Library/include/CSP/Systems/Assets/Material.h
Library/src/Multiplayer/Components/AnimatedModelSpaceComponent.cpp
Library/src/Multiplayer/Components/StaticModelSpaceComponent.cpp
Library/src/Systems/Assets/GLTFMaterial.cpp
Library/src/Systems/Assets/Material.cpp
Tests/src/InternalTests/MaterialTests.cpp
Tests/src/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp

- Added material overrides props to static/animated model components
- Setup tests for static/animated model components
- put scripted properties on hold as this is not part of p0 and quickjs has issues with maps

[OF-1442] feat: Material Overrides

---

Library/premake5.lua

With this change, the CSP Library project pulls in all markdown files in `Library\docs\source`, listing them in a `docs` directory alongside CSP source files.
This is intended to make it easier for developers to make changes to the documentation as an atomic operation, along with the corresponding code changes being made to the library itself. One powerful example is having all references to particular method show up across both the codebase itself _and_ documentation when searching for a term in the IDE.

[NT-0] refac: Including documentation in Library project

---

Library/src/CSPFoundation.cpp

Replacing an instance of the term 'foundation' that is emitted to client logs with the term 'CSP'.

[NT-0] refac: replacing foundation term

---

MultiplayerTestRunner/src/InternalUnitTests/Test_CLI.cpp

Our teamcity runners seem to be rejecting the std::pair comparison, even though they work fine locally.
Just workaround it to unblock things.

[NT-0] fix: Workaround CI std::pair comparisons

---

Library/include/CSP/Systems/Assets/Asset.h
Library/src/Systems/Assets/Asset.cpp
Library/src/Systems/Assets/AssetSystem.cpp
Tests/CSharp/src/Tests/AssetSystemTests.cs
Tests/Web/html/tests/assetsystem_tests.js
Tests/src/PublicAPITests/AssetSystemTests.cpp

To make the Asset class a full DTO, change the methods to properties. This will help simplify the C# Foundation layer & memory management wrapping.

Asset: make ThirdParty properties public, remove methods

---

Library/include/CSP/Systems/Spaces/Space.h
Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/src/Systems/Assets/AssetSystem.cpp
Library/src/Systems/Spaces/Space.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

- Passing the optional tags parameter as nullptr to UpdateSpaceMetadata now leaves the tags unchanged instead of resetting them.
- Add a getter/setter for tags in SpaceMetadataResult[s]Callback
- Add test cases to ensure non-regression

[OB-3939] fix: Passing tags as nullptr no longer resets tags

---

Examples/Basic Framework/Web/index.js
Examples/Initialising Foundation/CPlusPlus/InitialisingFoundation/InitialisingFoundation/InitialisingFoundation.cpp
Examples/Initialising Foundation/Web/index.js

CHS got in touch asking us to stop using the FOUNDATION_HELLO_WORLD tenant.
I'd been using it to repro a bug, having started from the web example.
The foundation tenant only appears in a few of our examples.
Update to CSP_HELLO_WORLD, which CHS recommends instead now. We shouldn't have the term "Foundation" in our docs anyhow.

[NT-0] doc: Update example tenant from FOUNDATION_HELLO_WORLD to CSP_HELLO_WORLD

---

Library/include/CSP/Systems/Assets/AssetSystem.h
Library/premake5.lua
Library/src/Systems/Assets/AssetSystem.cpp
Tests/src/PublicAPITests/MaterialTests.cpp

* Fixed wasm crash with blocking the main thread by replacing promise/future with a container of jobs which exists on the asset system to prevent data going out of scope
* Fixed issue with material ids not being set

[OF-1441] fix: wasm crash

---

MultiplayerTestRunner/include/ProcessDescriptors.h
MultiplayerTestRunner/include/TestIdentifiers.h
MultiplayerTestRunner/premake5.lua
MultiplayerTestRunner/src/Utils.cpp
MultiplayerTestRunner/src/Utils.h
Tests/premake5.lua
Tests/src/InternalTests/MultiplayerTestRunnerProcessTests.cpp
Tests/src/MultiplayerTestRunnerProcess.cpp
Tests/src/MultiplayerTestRunnerProcess.h
Tests/src/PublicAPITests/MultiPlayerTests.cpp
ThirdParty/tiny-process-library/.clang-format
ThirdParty/tiny-process-library/.gitignore
ThirdParty/tiny-process-library/.gitlab-ci.yml
ThirdParty/tiny-process-library/CMakeLists.txt
ThirdParty/tiny-process-library/LICENSE
ThirdParty/tiny-process-library/README.md
ThirdParty/tiny-process-library/examples.cpp
ThirdParty/tiny-process-library/process.cpp
ThirdParty/tiny-process-library/process.hpp
ThirdParty/tiny-process-library/process_unix.cpp
ThirdParty/tiny-process-library/process_win.cpp
ThirdParty/tiny-process-library/tests/CMakeLists.txt
ThirdParty/tiny-process-library/tests/io_test.cpp
ThirdParty/tiny-process-library/tests/multithread_test.cpp
ThirdParty/tiny-process-library/tests/open_close_test.cpp
ThirdParty/tiny-process-library/tests/path_test.cpp
generate_solution.bat

Integrates the previously written multiplayer test runner with the tests project. An example integration test is provided not so much to test the actual functionality, but to provide a template for additional tests going forward.
> [!TIP]
> Some reviewers may have missed the standup where I noted this implementation was pivoting from making a separate `MultiplayerTestManager` project towards direct integrations with the `Tests` library. This rethink was caused by the undue complexity of integrating just a subset of boost, and the need to find an alternate process library, which was much easier to integrate, and made a direct tests integration make sense. The `MultiplayerTestRunner` remains as it had before, a useful tool for direct running of CSP functionality. Due to the holidays, this …

[OF-1471] test: Integrate multiplayer test runner with Tests project

---

Library/src/Systems/Assets/AssetSystem.cpp

* Ensures AssetSystem::GetMarerials gracefully exits when an error occurs

[OF-1441] fix: elegantly fail when error

---

Library/include/CSP/Multiplayer/IEntitySerialiser.h
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.cpp
Library/src/Multiplayer/SignalRMsgPackEntitySerialiser.h

These methods are not at all called internally or in tests, and we confirmed with clients that they're not used downstream :
https://magnopus.slack.com/archives/C037VC209QT/p1737118085667259
Prior to the most recent change, these wern't even calling the correct overload to store vector data, so I'm pretty confident these can be ripped out.

[OF-1494] refac!: Remove unused serialization vector methods

---

Library/include/CSP/Systems/Log/LogSystem.h
Library/src/Systems/Log/LogSystem.cpp

Only log to the console and the log file if there is no log callback set by a client.

[OB-3785] fix: only log to console and file if there is no log callback

---

Library/include/CSP/Multiplayer/SpaceTransform.h
Library/src/Multiplayer/SpaceTransform.cpp
Tests/src/PublicAPITests/SpaceTransformTests.cpp

(This issue found during the warnings as errors sweep, i'm fixing it now, it's the final fix)
The existing implementation had several things wrong with it, one has to imagine it was never called anywhere, because this would be so apparent. Unfortunately, it was untested since the beginning.
Issues :
- [[nodiscard]] warning on normalize ignored, although post-rotation normalization is only needed to prevent cascading floating point errors
- The W component for glm::quat is the first argument, but for our vectors it is the last, all our quaternions were being constructed with nonsense values. (Strong typing please! Vector4 is inappropriate to store quaternions for precisely this reason)
- I don't think you can do complex compositions in this manner, separating the translation, scale and …

[OF-1494] fix: Fix SpaceTransform multiplication

---

Library/src/Web/EmscriptenWebClient/EmscriptenWebClient.cpp

Fix a silly warning for a not implemented function for emscripten builds. Only manifests in release builds, which is why it wasn't caught.
Yet another reason why unfinished functions and untested functions should not hit main.

[NT-0] fix: Emscripten release mode build warning

---

.github/README.md

Updating the links to the CSP documentation site in `README.md` to reference the new URL.

[NT-0] docs: Updated README links to the docs to use the new URL

---

Library/include/CSP/Systems/Assets/AssetSystem.h
Library/src/Systems/Assets/AssetSystem.cpp
Tests/src/PublicAPITests/MaterialTests.cpp

- Add parameters for metadata and tags to the create material method to support being able to filter them out from other types of assets
- Update the relevant tests

[NT-0] feat!: Add metadata and tag parameters to material creation

---

Library/include/CSP/Multiplayer/Components/ConversationSpaceComponent.h
Library/src/Multiplayer/Components/ConversationSpaceComponent.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

- Implemented OnLocalDelete for ConversationSpaceComponent to call DeleteConversation when the component is deleted
- Fixed issue with DeleteConversation not removing the entire conversation
- Added test to verify this

[OF-1388] feat: Conversation assets are now deleted when component is deleted

---

Tests/src/PublicAPITests/EventBusTests.cpp

This test is flaky, for reasons we can't track down. The flakiness pattern seems to be time based, in that it often consistently fails for hours at a time, before starting to pass again.
It is extremely frustrating to be disabling it, but it's blocking other PRs.
Will be logging a ticket to figure out what's going on here once this PR is approved.

[NT-0] test: Disable EventBusTests::EventCallbacksSystemsTest

---

PR_GUIDELINES.md

Add PR guidelines document capturing the decisions made in the recent team meeting.
For best effect, click "Display the rich diff" for this review.
I decided to place this at the root of the repo, as there is no "contributing" directory as yet. I'm tempted to make one, although until we have more than one document it doesn't feel worth it.
I know we have website docs, this doesn't feel like it belongs there though, this is extremely repo-specific. Open to suggestions on location.

[OF-1499] doc: Add PR guidelines

---

Library/include/CSP/Systems/Spaces/Space.h
Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/src/Systems/Spaces/Space.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

- Create getter for the IDs of users who accepted an invite. It works on the same principle as GetPendingInvites, except that it retrieves the user ID, not the email address.
- Improve pending invites test and add a comment
- Add a test for the accepted invites
- Update csp-services to the latest version so it contains the accepted endpoint wrapper

[OF-1523] feat: Add getter for ids of users who accepted invites

---

Library/src/Multiplayer/Script/ComponentBinding/AnimatedModelSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/AnimatedModelSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/AudioSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/AudioSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/AvatarSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/AvatarSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/CollisionSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/CollisionSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/ConversationSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/ConversationSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/FogSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/FogSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/ImageSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/ImageSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/LightSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/LightSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/ReflectionSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/ReflectionSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/TextSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/TextSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/ComponentBinding/VideoPlayerSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/VideoPlayerSpaceComponentScriptInterface.h

This is because our current version of quickjs does not support BigInt (64 bits ints), which led to an error if using BigInt in a script on Web, or an unsupported conversion warning if using a Number.
Now that we expose 32 bits ints, the web scripts no longer show an unsupported conversion warning when using a Number.
Breaking: This change requires the web client team to update their script interface to match the new types.

[OB-3917] fix! : change all int_64t exposed script parameters to int_32t

---

teamcity/Config.py

Reverts change [29613a8](https://github.com/magnopus-opensource/connected-spaces-platform/pull/623)
The addition of the iOS DebugStatic build meant that the Unity package exceeded the npmjs package limit.

[OF-1580] chore: Remove DebugStatic build from Unity package

---

Library/docs/terraform/cloudfront.tf

The `cloudfront.tf` script was written under the assumption it would be run on Linux, however our deploy agents on TeamCity are windows.
On windows, the line:
`command = "aws cloudfront create-invalidation --distribution-id ${aws_cloudfront_distribution.main.id} --paths /'*'"`
Should read:
`command = "aws cloudfront create-invalidation --distribution-id ${aws_cloudfront_distribution.main.id} --paths /*"`
ie - remove the single-quotes from this part at the end: `'*'"`
The change [has been tested](https://magnopus.teamcity.com/buildConfiguration/Olympus_OlympusFoundation_PublishDocumentation/283921) with our deploy pipeline and validated. So should be good to go.

[NT-0] fix: CSP docs deployment on windows machines

---

Library/include/CSP/Common/Array.h
Library/include/CSP/Common/String.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/include/CSP/Systems/Spaces/Space.h
Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/src/Common/String.cpp
Library/src/Systems/Spaces/Space.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Tests/src/InternalTests/CommonTypeTests/Array.cpp
Tests/src/InternalTests/CommonTypeTests/String.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

Tags are now on spaces directly, rather than bundled with the metadata, as they were before. 
This seems like a more natural design to me.
The consequences of this that you'll see in this PR:
- Any place where metadata was set, tags used to also be set ... they are no longer
- Tags are fundamental elements of a space now, much like the name and attributes
- Tags can be gotten from the `Space` object, and updated with `UpdateSpace`
Updating the services is also done in this PR, as it was a breaking change and needed code changes around it.

[OF-1577] feat!: Add tag controls to Space, removing them from the metadata prototype.

---

MultiplayerTestRunner/src/RunnableTests/CreateAvatar.cpp

So, i never connected the flaky avatar test to the fact that it was the MultiplayerTestRunner one I wrote. If I had, I would have jumped on this earlier to satisfy my stupid pride.
I would say about 15-20% of the time this fails on CI, never locally though, ran it for 15 minutes in a loop.
Unfortunately, I don't really know why it's failing. It's possible a CHS processing delay may cause it, but I've assumed up until now receiving a result is like an ACID transaction, when perhaps it more means "Request acknowledged?" (Documentation for this sort of stuff exists? It might. CHS feels like such a black box at the moment 😖 )
In any case, let's try this. I'll rerun the functional tests on the CI 4 or 5 times from this PR to see if it stays stable, and if so put it in. Fingers crossed eh 🤞

[NT-0] test: Hail Mary attempt to fix avatar test

---

Tests/src/PublicAPITests/MultiplayerTestRunnerProcessTests.cpp

They touch the network, shouldn't be internal.
From low hanging fruit session.

[OF-1569] test: Change multiplayertestrunner tests to be public tests

---

Library/include/CSP/CSPFoundation.h
Library/src/CSPFoundation.cpp
Library/src/Multiplayer/SignalR/POCOSignalRClient/POCOSignalRClient.cpp
Library/src/Multiplayer/SignalR/POCOSignalRClient/POCOSignalRClient.h
MultiplayerTestRunner/src/Main.cpp
Tests/src/InternalTests/WebClientTests.cpp
Tests/src/InternalTests/WebSocketClientTests.cpp
Tests/src/MultiplayerTestRunnerProcess.cpp
Tests/src/PublicAPITests/ComponentTests/AnimatedModelComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/StaticModelComponentTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/MultiplayerTestRunnerProcessTests.cpp
Tests/src/PublicAPITests/SettingsSystemTests.cpp
Tests/src/PublicAPITests/SpaceSystemTests.cpp

**tl;dr: Local CHS works now, but a couple of tests have (probably timing related) issues that still need to be shaken out. Full test suite runs are 4-5 minutes long.**
Do the CSP work to allow local CHS to function. 
This changeset does a fair amount more than what was specified in the ticket. There had as of yet been no thought put into the issues with the multiplayer signalR connection. It was never going to just work, so the changes to get that going have been done here too.
This change involves, broadly, 3 things.
- ✔️ Remove all hard-coded URI references to the cloud services throughout the codebase.
- ✔️ Revamp our URI handling for the multiplayer signalR connection
- 🟡 Fix any tests that are demonstrating new issues from the faster cloud services response. 
The first two are …

[OF-1575] Enable Local CHS, Remove hard-coded URIs, migrate multiplayer URI handling.

---

Library/include/CSP/Systems/Users/Authentication.h
Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/Users/Authentication.cpp
Library/src/Systems/Users/Authentication.h
Library/src/Systems/Users/UserSystem.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

Expose ServiceProxyPost and allow user to pass their own token info parameters. 
Add a new test and check error messages are not emitted in the log for both the new ServiceProxyPost test and the old AgoraUserToken tests

[OF-1447] feat: add ability to post to service proxy directly

---

Library/include/CSP/Multiplayer/Conversation/ConversationSystem.h
Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Common/Continuations.h
Library/src/Multiplayer/Conversation/ConversationSystem.cpp
Library/src/Multiplayer/EventBus.cpp
Library/src/Multiplayer/MultiplayerConnection.cpp
Library/src/Multiplayer/NetworkEventManagerImpl.cpp
Library/src/Multiplayer/NetworkEventManagerImpl.h
Library/src/Multiplayer/SignalR/ISignalRConnection.h
Library/src/Multiplayer/SignalR/SignalRConnection.cpp
Library/src/Multiplayer/SignalR/SignalRConnection.h
Library/src/Multiplayer/SpaceEntitySystem.cpp
Library/src/Systems/Spaces/SpaceSystem.cpp
Library/src/Systems/Users/UserSystem.cpp
Tests/src/Mocks/SignalRConnectionMock.h
Tests/src/PublicAPITests/EventBusTests.cpp
Tests/src/PublicAPITests/GeneralContinuationsTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicTestBase.cpp

> [!TIP]
>This benefits from a commit-by-commit review
Refactor the `Connect` function to continuations. 
Several refactorings are done as part of this work:
- Create a mocking pattern via `SignalRClient`, and show the first use of full type mocks in our tests.
- Use that pattern to test untriggerable network errors through the `Connect` flow.
- Slightly evolve the error handling for the Connection Object, to at least try to give some context
- Rename existing continuations utilities to `HTTP`, to better represent their difference from Multiplayer results.
Three points jump out to me having done this work, for future consideration.
- Our conversion from SignalR errors to our own error reporting mechanism is rather confused.
- There are four callbacks in play, which is too many and very …

[OF-1585] refac: Connect Continuations

---

Library/src/Multiplayer/Script/ComponentBinding/AvatarSpaceComponentScriptInterface.h

The avatar component `HandRotation` and `HeadRotation` were declared with the wrong types in the component script interface header. This PR updates the declaration to match the definition and component property types.

[NT-0] fix: Correct script property declaration types for avatar component HandRotation and HeadRotation properties

---

Tests/src/InternalTests/WebClientTests.cpp

Added missing API key to the header for the failing requests.
Payload.AddHeader(CSP_TEXT("x-api-key"), CSP_TEXT("reqres-free-v1"));
We use an external service (https://reqres.in/) for testing against a real API, and there requirements seem to have changed.

[NT-0] test: API key now required for requests

---

Tests/src/InternalTests/WebClientTests.cpp

We literally just missed this due to a case of collective blindness.
EDIT: I've also added api keys to all other methods that use this service, as the get query seemed to not be consistent on whether it needed it or not, which may happen for other queries down the line.

[OF-1624] fix: Add missing auth header to web client test

---

Library/premake5.lua
Tools/Emscripten/EmscriptenFullBuildAndConfigure.bat
Tools/Emscripten/EmscriptenFullBuildAndConfigure.sh
premake5.lua

In theory, compiling in node should be fine, its the emscripten default, it's meant to check which environment it is in by design. However, web clients couldn't consume it without making modifications. Therefore we'll branch for now.
Makes the default build mode without node, as it has always been.

[OF-1623] build: Add ability to compile optionally with or without nodeJS for WASM

---

Library/include/CSP/Multiplayer/SpaceEntity.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Common/Continuations.h
Library/src/Multiplayer/SignalR/ISignalRConnection.h
Library/src/Multiplayer/SignalR/SignalRConnection.cpp
Library/src/Multiplayer/SignalR/SignalRConnection.h
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp
Tests/src/Mocks/SignalRConnectionMock.h
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/SpaceEntitySystemTests.cpp

Refactor CreateAvatar to be linear.
This adds continuation capability to `SignalRConnection::Invoke`, which is the core of this ticket.
As this is an internal change and we're interested mostly in how it handles being interrupted, testing is performed on a continuation by continuation basis via mocks, mocking failures in the `SignalRConnection`.
A new continuation utility is added to unwrap types that come out of `Invoke` (and other SignalR methods I suspect). This utility introduces a `std::conditional` pattern using `if constexpr` to optionally forward or not forward the input arg to subsequent continuations.
You may be surprised by the double construct of the avatar. This _is_ unfortunate, but is explained in a large comment in the file.
> [!Warning]
> Do not review the [first …

[OF-1586] refac: CreateAvatar Continuations

---

Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp
Tests/src/PublicAPITests/MaterialTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/PointOfInterestSystemTests.cpp
Tests/src/PublicAPITests/UserSystemTests.cpp

there are two parts to this PR. it is debatable whether the second part should stay in this PR (if it doesn't, it should go in the ticket that will fix the conversation tests). the obvious argument in favour of keeping this change in is that local CHS is ready to use in PR checks.
Part 1: disable the problematic tests. there are 8 of them. More info about the failures in the story. Will also add dedicated new stories, see links in the story.
Part 2: fix crash in local CHS (a conversation test was calling the hard-coded live endpoint, leading to a crash). this is the part that arguably should be moved to the conversation story.

[OF-1608] Disable the tests that are problematic on local CHS

---

Library/include/CSP/Systems/Spaces/SpaceSystem.h
Library/src/Systems/Spaces/SpaceSystem.cpp

On the CI we currently have two flaky test introduced by 021dffc5bbae6e298a5aac8a77197160a81c9b22
On review of the change it seems that behaviour has changed from a linear deletion process to non blocking async workflow. This resulted in a race condition where we are deleting the same resources, in the event these are executed in the wrong order would result in the tests crashing. 
The DELETE /api/v1/spaces/{SpaceId} endpoint will delete the thumbnail and metadata, which make the previous calls redundant, and removal prevent the race condition as only a single action will attempt to delete a resource. 
```
DELETE /api/v1/spaces/{SpaceId}
Locates the Space by its unique groupId represented here as spaceId and the associated objects that belong to it
and deletes it from the data store. This …
```

[NT-0] fix: removed redundant removal of thumbnail and metadata

---

Tests/src/PublicAPITests/MaterialTests.cpp

Fix MaterialEventTest and MaterialAssetEventTest by shamelessly reusing the fix for https://github.com/magnopus-opensource/connected-spaces-platform/pull/688.
Note that this PR has been re-purposed, as when I opened it I only had a fix for the crash in MaterialEventTest (not for the test failure), but now I have a real fix, which happens to also fix a second test, MaterialAssetEventTest.
Therefore, if I haven't squashed yet, please ignore the first commit, as it has the crash fix and not the fix fix.
Reasons why I have reasonable grounds to think that the transient failure is fixed:
- have 1000 out of 1000 successful runs of each of the 2 aforementioned tests, on local CHS, on my local machine. Note that before the fix (this morning), it wouldn't go past 5 or 6 runs at most before …

[NT-0] fix: fix MaterialEventTest and MaterialAssetEventTest 

---

Library/include/CSP/Multiplayer/EventBus.h
Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/include/CSP/Multiplayer/SpaceEntity.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Multiplayer/Election/ClientElectionManager.cpp
Library/src/Multiplayer/EventBus.cpp
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp
Library/src/Systems/SystemsManager.cpp

Remove friends from SpaceEntity, SpaceEntitySystem, EventBus and MultiplayerConnection.
Create new getters and setters where private members were used directly, and make necessary private methods public (using CSP_NO_EXPORT, to avoid unnecessary exports).
Add docstrings on every new or changed function.

[OF-1633] chore: remove friends from SpaceEntity et al.

---

Library/include/CSP/Multiplayer/SpaceEntity.h
Library/src/Multiplayer/MCS/MCSTypes.cpp
Library/src/Multiplayer/MCS/MCSTypes.h
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp
Tests/src/InternalTests/MCSTests.cpp

It is IsPersistent.
This typo has been present, and ignored, in the last 3 or 4 PRs that touched space entity. I got tired of seeing it.
Unfortunately, ObjectMessage::GetIsPersistent() is public (defined in MCSTypes.h), so I marked the change as breaking...

[NT-0] fix!: fix IsPersistant typo

---

Library/include/CSP/Multiplayer/SpaceEntitySystem.h

Removing a spurious colon that was tripping up doxygen whilst generating documentation.
Validation of this fix can be found [here](https://magnopus.teamcity.com/buildConfiguration/Olympus_Foundation_Documentation_GenerateDocumentation?).

[NT-0] fix: Documentation generation

---

Library/include/CSP/Multiplayer/SpaceEntity.h
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp

In the following circumstance, we can cause SpaceEntity::ComponentsLock to be locked twice in the same code path, causing the program to lock up:
- A script exists that modifies a component property when executed
- The script source is then updated
- This causes a patch to be sent, changing the script source
- A patch is received by another client, which locks the ComponentsLock mutex
- ScriptSpaceComponent overrides SetPropertyFromPatch to get them to re-run the script when changed
- This causes the script to run, and the script modifies a property
- Modifying this property calls SpaceEntity::AddDirtyComponent, which also locks ComponentsLock
- The program then freezes
We have currently fixed this by introducing a recursive_mutex, which isn't the best way forward. Ideally, we want to …

[OB-4284] fix: Prevent SpaceEntity::ComponentsLock from doubling locking

---

MultiplayerTestRunner/src/RunnableTests/CreateConversation.cpp
Tests/src/PublicAPITests/ComponentTests/ConversationComponentTests.cpp

ConversationComponentSecondClientEventDelayTest -
- Created a second user for the Test runner
- New user has to be set as moderator  to create test object in the space
- Had to disable rate limiting so all patches were sent
ConversationComponentPermissionsTest -
- Had to disable rate limiting so all patches were sent
- Reordered EnterSpace to ensure callback is set before entities are retrieved.

[OF-1645] Fix: Conversation tests

---

Library/CSharpWrapper/src/NativeClassWrapper.cs
Tools/WrapperGenerator/Templates/CSharp/Partials/Class/TaskMethod.mustache

In some cases, the C++ layer will use `nullptr` in callbacks or return values to indicate failure or a missing object. The C# wrapper generator currently wraps these in a managed object instance; calling any function or property on this object will result in a segfault.
The expected behavior in C# is that objects are valid or `null`.
This PR will:
* Ensure that invalid `NativeClassWrapper` instances cannot be created
* Return a C# `null` any time a native `nullptr` is produced

Prevent referencing native nullptrs

---

Library/include/CSP/Common/Interfaces/IRealtimeEngine.h
Library/include/CSP/Multiplayer/Components/AvatarSpaceComponent.h
Tools/WrapperGenerator/Templates/CSharp/Class.mustache

Part of an ongoing modularity effort, create an IRealtimeEngine interface, containing the proposed interface for what is currently the multiplayer module.
This is mostly a port of `SpaceEntitySystem`, removing all the interfaces that are not relevent for a generic multi/single-user abstraction, as well as all the interfaces that are only used internally to what will become the RealtimeEngine module. See the documentation at the bottom of the file for a list of all the functions that have not made the interface, as well as the ones planned for the Multi user concretion.
> [!NOTE]  
> The biggest swing here is the removal of `AddEntity`, which is used [here ](https://github.com/magnopus/ichabod/blob/9bcfe3d072fd4498f5bbd7dcfd2f6e301fe46e9c/ichabod/space_manager.cpp#L1554)in ichabod, …

[OF-1669] refac: Create IRealtimeEngine interface

---

Library/CSharpWrapper/src/NativeClassWrapper.cs
Tools/WrapperGenerator/Templates/CSharp/Partials/Class/TaskMethod.mustache

Reverts magnopus-opensource/connected-spaces-platform#702
While we agree this is a good change, it breaks some behaviour in Array<> that relies on being able to create null instances.
See [this conversation on Slack](https://magnopus.slack.com/archives/C02TKEGRJE6/p1749727816407889).

Revert "Prevent referencing native nullptrs"

---

Library/include/CSP/Multiplayer/Components/AvatarSpaceComponent.h
Library/include/CSP/Multiplayer/SpaceEntitySystem.h
Library/src/Multiplayer/Components/AvatarSpaceComponent.cpp
Library/src/Multiplayer/Script/ComponentBinding/AvatarSpaceComponentScriptInterface.cpp
Library/src/Multiplayer/Script/ComponentBinding/AvatarSpaceComponentScriptInterface.h
Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Library/src/Multiplayer/SpaceEntitySystem.cpp
MultiplayerTestRunner/src/RunnableTests/CreateAvatar.cpp
Tests/src/InternalTests/SpaceEntityTests.cpp
Tests/src/PublicAPITests/ComponentTests/AvatarComponentTests.cpp
Tests/src/PublicAPITests/ComponentTests/PortalComponentTests.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp
Tests/src/PublicAPITests/ScriptSystemTests.cpp
Tests/src/PublicAPITests/SpaceEntitySystemTests.cpp

Added support for visibility control to the AvatarSpaceComponent.
- Implemented the IVisibleComponent interface in the AvatarSpaceComponent.
- Updated the Avatar component script interface to add script support for the new IsVisible and IsARVisible properties.
- Updated Entity script bindings to include new visibility properties.
- Updated the SpaceEntitySystem Avatar creation methods to take an initial Avatar visibility argument.
- Added tests to cover the new visibility property for the Avatar component.
Only 3 commits but probably easier to review them individually as the last commit is just concerned with minor improvements to the existing tests that required updates as part of this work.
> [!NOTE]
> There were no existing tests for the Avatar Space Component so I have added two, one …

[OF-1686] feat!: Avatar Space visibility

---

Tests/src/PublicAPITests/UserSystemTests.cpp

What the title says, really. The tests started passing, presumably after CHS implemented proxy services in the local tenant. I have updated my CHS image this morning, and I hadn't in a while. So the change might have already been there longer.
- Passed using local CHS on my local machine, 55 successful runs each so far. I killed it after it reached 100 successful successive runs for each
- Green local CHS CI job: https://magnopus.teamcity.com/buildConfiguration/Olympus_Foundation_X64_TestsLocalChsInstance/291280 (see also below, in the checks)
- Green live CHS CI job: https://magnopus.teamcity.com/buildConfiguration/Olympus_Foundation_X64_FunctionalTests/291295?buildTab=overview&focusLine=NaN

[OF-1646] fix: re-instate the Agora tests after CHS enabled proxy services on the local tenant

---

Library/src/Multiplayer/Script/EntityScriptBinding.cpp
Tests/src/PublicAPITests/ComponentTests/CinematicCameraComponentTests.cpp

[OF-1722] feat: isEnabled for cinematic camera scripting
- Added support for isEnabled in the cinematic camera script interface so it can be enabled/disabled from scripts
[OF-1722]: https://magnopus.atlassian.net/browse/OF-1722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OF-1722] feat: isEnabled for cinematic camera scripting

---

.github/workflows/add-pr-guidance.yml

When a pull request is created from a fork, GitHub Actions workflows run in a more restricted context for security reasons. The `pull_request_target` event is used to give the workflow the appropriate write permissions and runs the workflow in the context of the base repository (the one the PR is targeting).
The `pull_request_target` event runs with elevated permissions so we must be careful with its use in workflows. We can mitigate this risk by not allowing workflows with this event to check out and run untrusted code from the pull request or to run untrusted scripts. 
This change means that when a PR is raised from a fork, the PR Guidance comment will be added.

[NT-0] ci: Update the PR Guidance workflow to support forks

---

Library/include/CSP/Multiplayer/MultiPlayerConnection.h
Library/src/Multiplayer/MultiplayerConnection.cpp
Library/src/Multiplayer/SignalR/POCOSignalRClient/POCOSignalRClient.cpp
Library/src/Multiplayer/SignalR/POCOSignalRClient/POCOSignalRClient.h
Library/src/Multiplayer/SignalR/SignalRClient.cpp
Library/src/Multiplayer/SignalR/SignalRConnection.cpp
Library/src/Systems/Users/UserSystem.cpp
Tests/src/InternalTests/PlatformTestUtils.cpp
Tests/src/PublicAPITests/MultiPlayerTests.cpp

This ticket addressed the CSPFoundation dependency in POCOSignalrRClient. The Multiplayer URI is now passed through. This may seem confusing as it isn't done for the Emscripten version, but Emscripten uses a different URI, which is passed in when Start is called. This URI is modified by SignalR, which is needed for Emscripten, but not for POCO. I don't claim to understand the reasons for this modification.
I also removed a couple of redundant includes in the PR.

[OF-1708] feat: Break system dependencies on WebSocketClient

---

Library/include/CSP/Multiplayer/NetworkEventBus.h
Library/src/Multiplayer/NetworkEventBus.cpp
Tests/src/PublicAPITests/EventBusTests.cpp
WasmTesting/csp-wasm.test.ts
WasmTesting/html_tests/SendReceiveNetworkEvent.html

Workaround the wrapper generator bug with shorthand signature generation.
There is an issue where if the return type of the accepting function is different from the return type of the registering callback (at least in cases like this where we're registering for later behaviour, not making a task/promise sort of construct), then the shorthand type sig used for binding callbacks will generate wrong, using the return type of the enclosing function.
Coincidently, we'd never done this before.
Wrapper generator bug still exists, this just avoids it.
Add a regression test, which I saw fails before the change, and passes after.
**Breaking changes**
Return types of following methods changed from bool -> void
- NetworkEventBus::ListenNetworkEvent(NetworkEventRegistration, NetworkEventCallback)
- …

[OF-1732] fix!: Shorthand signature wrapper gen bug workaround

---

Library/include/CSP/Systems/Settings/SettingsCollection.h
Library/include/CSP/Systems/Settings/SettingsSystem.h
Library/src/Systems/Settings/SettingsCollection.cpp
Library/src/Systems/Settings/SettingsSystem.cpp
Tests/src/PublicAPITests/SettingsSystemTests.cpp
Tests/src/PublicTestBase.cpp
Tests/src/PublicTestBase.h

Currently, clients are unable to discern between "a user that has never set an avatar" and "a user that has explicitly chosen to hide their avatar".
The PR updated the user settings and [SetAvatarInfo](https://github.com/magnopus-opensource/connected-spaces-platform/blob/3897cff42ce745f3088c59585cfdb636019f9eca/Library/include/CSP/Systems/Settings/SettingsSystem.h#L141) API to allow clients to reason about the state of the user. 
The PR contains the following changes: 
- Introduce a new bool to track if the avatar should be visible or not.
- Updated the public API to expose the new bool to clients.
- Included validation for the new property in tests.
Many approaches could have been taken to resolve this; however, there was a previous discussion as a team for a suitable resolution. Please …

[OF-1728] feat!: user settings support avatar visibility information

---

Tests/src/PublicAPITests/ComponentTests/CustomComponentTests.cpp
Tests/src/PublicAPITests/HotspotSequenceTests.cpp

We're not 100% sure if this change is the cause of the flakey test, but it should be there anyway. I also removed a duplicate delay from the custom component test.

[NT-0] fix: Add chs database write to sequence persistence test

---

Library/include/CSP/Common/Interfaces/IRealtimeEngine.h

Left in from initial iterations, very misleading.

[NT-0] doc: Fix innapropriate RealtimeEngine lifetime documentation

---

Tools/WrapperGenerator/tests/test_parser.py

Added fairly thorough tests for the `__parse_type()` function. These tests cover _almost_ every line of the function.
These tests build on each other, starting from checking simple types (e.g. `test_parse_primitive_type`), then using the parser to construct tests for templated types (`test_parse_template_type`) to finally checking templated `std::function<>` types with templated arguments.
`test_parse_pointer_to_pointer_to_pointer_type_fails` demonstrates that there are certain edge case types (`int***`) that the parser handles incorrectly.

Tests for `Parser.__parse_type()`

---

.github/README.md

Several URLs in the readme were directing the browser to the legacy home of CSP documentation.
Fixed by updating to the corresponding URLs under the new domain.

[NT-0] docs: Updated documentation URLs in readme

---

Library/src/Multiplayer/OnlineRealtimeEngine.cpp

This is an expected, per-frame, path, so don't want to spam except on the highest diagnostic level.

[NT-0] Change no-patch send log to VeryVerbose

---

Library/include/CSP/Systems/Users/UserSystem.h
Library/src/Systems/SystemBase.cpp
Library/src/Systems/SystemsManager.cpp
Library/src/Systems/Users/UserSystem.cpp

We had a circular dependency issue in the SystemsManager due to SignalR requiring the AuthContext from the UserSystem for construction. To get around this we pass nullptr to the UserSystem ctor for the NetworkEventBus, and then call a newly introduced  method to set it after the NetworkEventBus has been constructed.

[NT-0] fix: Resolve initialization ordering issue

---

Library/include/CSP/Systems/Analytics/AnalyticsSystem.h
Library/src/Systems/Analytics/AnalyticsSystem.cpp
Tests/src/PublicAPITests/AnalyticsSystemTests.cpp

Added two new methods to the AnalyticsSystem; `BatchAnalyticsEvent` and `FlushAnalyticsEvents`.
The `BatchAnalyticsEvent` method makes it possible to add an analytic event to a queue to be sent to MCS later as part of a batch.
The queue will be processed when one of the following conditions is met:
1. The time since the last batch was sent reaches the batch rate (default 60 seconds).
2. The number of events in the queue reaches the maximum batch size (default 25 events).
3. The client application calls FlushAnalyticsEvents() as part of their log out or shut down procedure to force the batch to be sent.
The `FlushAnalyticsEvents` method will trigger immediate dispatch of the Analytics Records queue to MCS. This method is designed to be called as part of a client applications log out and …

[OF-1739] test: Add batched analytics events

---

Library/include/CSP/Multiplayer/SpaceEntity.h
Library/src/Multiplayer/PatchUtils.h
Library/src/Multiplayer/SpaceEntity.cpp
Library/src/Multiplayer/SpaceEntityStatePatcher.h
Tests/src/PublicAPITests/RealtimeEngineEntityTests.cpp

I would advise reviewing [OF-1761](https://github.com/magnopus-opensource/connected-spaces-platform/pull/792) first, as this merges into that branch.
We were only checking if the values were the same in our StatePatcher::SetDirtyProperty, which isn't used on the offline version.
Instead of adding a conditional check in every setter, I created a generic, templated setter with this extra conditional in. This cuts out a lot of code from SpaceEntity.
[OF-1761]: https://magnopus.atlassian.net/browse/OF-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[OB-4678] Stop SpaceEntity::UpdateCallback firing wven when the value is the same for OfflineEngine.

---

Tests/src/PublicAPITests/PointOfInterestSystemTests.cpp

The previous failing test worked out of the box on local CHS; it was likely that, due to confusion around local CHS at the time, this was not supported in the local version on the developer machine, but worked as intended on CI due to the latest version of the services being pulled. 
Following this, I took the opportunity to evaluate the current state of the test and coverage. This highlighted a few separate problems that have been fixed in this PR:
- Previously disabled tests have been reinstated 
- We did not have a direct test for the delete operation; this has been added 
- There were POI artefacts that persisted from the test runs; tests have been updated to remove the created POIs
- An additional test has been added for testing the negative of `GetPOIInsideCircularAreaTest`
Overall, …

[OF-1649] fix and re enable the poi tests

---

Library/include/CSP/Common/ReplicatedValue.h
Library/src/Common/ReplicatedValue.cpp
Library/src/Multiplayer/MCSComponentPacker.cpp
Tests/src/PublicAPITests/ReplicatedValueTests.cpp
Tests/src/PublicAPITests/ReplicatedValueTests2.cpp

This refactors our ReplicatedValue implementation use a std::variant instead of a union. This gives us a lot more power when using this type from within CSP, as we can use visit/compile-time type checking instead of runtime conditionals. An example of this exists in this PR when updating MCSComponentPacker::CreateItemComponentData to use std::visit. 
This change will also allow us to further streamline our ReplicatedValue conversions, as we now have access to templated setters and getters.

[OF-1511] Update ReplicatedValue to use a variant internally

---

Library/include/CSP/Systems/ExternalServices/ExternalServiceInvocation.h
Library/include/CSP/Systems/ExternalServices/ExternalServiceProxySystem.h
Library/src/Systems/ExternalServices/ExternalServiceInvocation.cpp
Library/src/Systems/ExternalServices/ExternalServiceProxySystem.cpp
Tests/src/PublicAPITests/ExternalServicesTests.cpp

It was pointed to me that we cannot assume any schema in the Json data returned via the external service proxy services.
This is because the proxy service is assumed to simply acts as a router for invoking operations on external services, and it is intended to feed the results of those operations directly back to the caller.
To account for that, this change refactors the result class used by the external service system into two classes. One generic class for returning the result payload with no tampering, and another for the Agora specialization.
The generic result class is used by `ExternalServiceProxySystem::InvokeOperation`, and returns the full string value of the `operationResult` Json field in the returned payload.
The specialized class is used by …

[OF-1796] feat: Generic ExternalService result processing

---

Library/src/Multiplayer/MCS/MCSTypes.cpp

This is not at all a real fix, it's just a patch we can choose to apply that will allow Unity ios to load old spaces in the same way the other clients currently can.
Testing this would imply either threading the log system down, inventing a whole new callback pattern, or even just moving this catch, which isn't something I'm willing to do for an off book fix like this. 
We should discuss this in standup, not sure if we should merge this or not, just putting it up to have it ready.
See [here ](https://magnopus.atlassian.net/browse/OB-4420?focusedCommentId=412476)for more.

[OB-4420] Add catch-all to allow Unity iOS to load old incompatible spaces
